### ISSUE TITLE
Cannot use GitHub backend

### ISSUE THREAD

**Issue by HansG9** [sveltia/sveltia-cms#103]
I try to use the GitHub backend but sveltiacms just shows the ability to "Work with Local Repository" instead of a login button.
My config.yml (all capitalized words normally are replaced with my credentials):

backend:
  name: "github"
  repo: "ME/MYREPO"
  branch: "main" # Branch to update (optional; defaults to master)
  base_url: "https://api.MYURL.com"
  auth_endpoint: "auth"

**Comment by kyoshino** [comment]
Thanks for reporting the issue. Hmm, not sure what’s happening. I just tested with my client’s Sveltia CMS instance, but it showed the Sign In with GitHub button as expected.

Just in case: Are you using Sveltia CMS remotely, right? If you’re [running it locally](https://github.com/sveltia/sveltia-cms?tab=readme-ov-file#work-with-a-local-git-repository), the Work with Local Repository button will always appear. (Technically you can use GitHub directly from a local instance, but there is no UI for that)

**Comment by kyoshino** [comment]
Ah got it! Then it’s rather better to work with a local repository because changes will not be committed 🙂 

Well, I’ll create a demo site once the “test” backend is supported!
