### ISSUE TITLE
Feature Request: Widget `email`

### ISSUE THREAD

**Issue by samtrion** [sveltia/sveltia-cms#107]
For validating email addresses based on the browser implementation. As this is already significantly more efficient than any regex/pattern matching.

**Comment by samtrion** [comment]
Thats `true`, not every browser is great at this. But this is a starting point, you can extend.

Functionality like `multiple` and `readonly` are already given.

**Comment by kyoshino** [comment]
I’ll just add the `type` property to the String widget because the UI is the same.
