### ISSUE TITLE
Feature Request: Ability to disable a field in preview

### ISSUE THREAD

**Issue by samtrion** [sveltia/sveltia-cms#108]
In most cases when displaying a page, I only need the title, summary and text for the preview. Therefore, it would be nice if there was a way to disable fields for the preview view.

**Comment by kyoshino** [comment]
I think it’s easy. Just like the [collection-level preview setting](https://decapcms.org/docs/configuration-options/#editor), I could add support for the field-level `preview` property.

```yaml
preview: false
```
