### ISSUE TITLE
Unwanted file-extension-change (`.svg` -> `.svg+xml`)

### ISSUE THREAD

**Issue by frankbits** [sveltia/sveltia-cms#11]
The filename generated by #9 for an 'svg'-file has the extension `.svg+xml`.
While the Mime-Type is `image/svg+xml`, this should probably be `.svg`
[Registration of media type image/svg+xml](https://www.w3.org/TR/SVG/mimereg.html)
In any case, should the extension not change when uploading an `.svg´-file

**Comment by kyoshino** [comment]
Thanks for reporting! The fix is coming with the next patch release 🫶
