### ISSUE TITLE
Feature Request: ValuePrefix/-Suffix for Widget `string`

### ISSUE THREAD

**Issue by samtrion** [sveltia/sveltia-cms#110]
I would like to strongly structure certain areas of my website and assign the `translationKey` uniformly. e.g. the `translationKey` of my blog posts should be pre-assigned with `post-`. This value prefix should not be editable.

Unfortunately, I got this idea from the existing `prefix` / `suffix` implementation, but there is a different functionality here.

**Comment by kyoshino** [comment]
Well yes, I’ve implemented https://github.com/decaporg/decap-cms/pull/6836 a few weeks ago, but I think `prefix` and `suffix` for the UI visibility purpose are ill-named. Another PR https://github.com/decaporg/decap-cms/pull/6675 I have also implemented uses `prefix` in the right way.

I think no one uses it in Sveltia CMS yet; I could rename the current `prefix`/`suffix` properties to something else and implement this as `prefix`/`suffix`.

**Comment by samtrion** [comment]
> I think no one uses it in Sveltia CMS yet; I could rename the current `prefix`/`suffix` properties to something else, say `before_input`/`after_input`, and implement this as `prefix`/`suffix`.

Sounds promising.
