### ISSUE TITLE
Feature Request: Allow Markdown Syntax for `hint`

### ISSUE THREAD

**Issue by samtrion** [sveltia/sveltia-cms#114]
For better formatting of the fields, using Markdown syntax for the field properties `hint` would be advantageous. This would enable providing additional information with a link or emphasizing keywords.

Related to #113

**Comment by kyoshino** [comment]
In Sveltia CMS, you can already use Markdown for `hint` while it’s not supported yet in Netlify/Decap CMS as per https://github.com/decaporg/decap-cms/issues/3759. My client’s Sveltia CMS configuration has `hint` with Markdown, actually.

**Comment by samtrion** [comment]
My fault, didn't tried this for `hint`. Only for `before_input` and `after_input`

**Comment by kyoshino** [comment]
Hmm, the [Decap doc](https://decapcms.org/docs/widgets/) says “Accepts markdown for bold, italic, strikethrough, and links” so it _may be_ supported. I haven’t tested it yet.

**Comment by kyoshino** [comment]
Just tested Netlify CMS used by one of my clients. It does support Markdown in `hint` 🙂
