### ISSUE TITLE
Unable to display image defined in markdown within preview

### ISSUE THREAD

**Issue by samtrion** [sveltia/sveltia-cms#115]
It is not possible for me to display linked images correctly in Markdown. These are mainly images that are stored on the same level as the index.md file. On the published page itself is everything fine. I already tried to set `media_folder` and `public_folder` for this collection to `""`.

```markdown
Some text .... ![Description](imagename.png) More Text...
```

Result:
![image](https://github.com/sveltia/sveltia-cms/assets/3283596/39b1cbce-80a7-4d7d-91d2-c4da18060e5c)

HTML:
```html
<p>
  <img src="microsoft-mslearn-architect-info.en.png" alt="Countdown in hours">
  This is followed by hour-by-hour information on when the renewal exam will be available and a list of available learning paths and modules that can still be taken during the preparation time. Due to technological development, some modules are updated or new modules are added, so it is worth taking a look regularly.
</p>
```

**Comment by kyoshino** [comment]
The preview has been fixed, but Sveltia CMS actually doesn’t have a Markdown editor yet. I’ll finish the work by the end of the month.
