### ISSUE TITLE
Hide `compute` field in editor pane

### ISSUE THREAD

**Issue by samtrion** [sveltia/sveltia-cms#121]
To avoid confusing the user, I would like to hide `compute` fields in the editor.

e.g.
```diff
label: Translation Key
name: translationKey
widget: compute
value: post-{{fields.slug}}
i18n: duplicate
-preview: false
+hide: true
```

**Comment by kyoshino** [comment]
Ah, I’m misunderstanding. The `compute` field should be hidden in the editor, not preview. I could simply hide it without configuration because showing it in the editor isn’t useful.

**Comment by kyoshino** [comment]
<img width="516" alt="Screenshot 2024-03-13 at 6 59 17 PM" src="https://github.com/sveltia/sveltia-cms/assets/2929505/09e1ebf7-8a4b-47bc-8c6b-c22c3b9f90ec">
