### ISSUE TITLE
local development not working after recent update

### ISSUE THREAD

**Issue by sardarms** [sveltia/sveltia-cms#128]
I was using the cms without any problem for a while now. But after the recent updates, it seems like, it is not working anymore. I am getting the below message: 

![image](https://github.com/sveltia/sveltia-cms/assets/83923880/668b6f2e-5c80-4259-8e54-7960f2fe976c)

I am using Hugo. My Config: 

```local_backend: true

media_folder: static/files
public_folder: /files

collections:

name: 'post'
label: 'Posts'
folder: 'content/post'
create: true
slug: '{{fields.slug}}'
editor:
preview: true
fields:
{ label: 'Title', name: 'title', widget: 'string' }
{ label: 'Slug', name: 'slug', widget: 'string' }
{ label: 'Publish Date', name: 'date', widget: 'datetime', required: false }
{ label: "Weight", name: "weight", widget: "number", required: false }
{ label: "Featured image", name: "feature_image", widget: "image", required: false }
{ label: "Description for SEO", name: "description", widget: "string", required: false }
{ label: "Categories", name: "categories", widget: "list", required: false, field: { name: text, label: Text, widget: string } }
{ label: "Author", name: "author", widget: "string", required: false }
{ label: "Body", name: "body", widget: "markdown" }
```

When I try to use http://localhost:1313/admin/ and show the local root folder, it shows the error. However, one of my colleagues who also use the CMS with hugo, has no issue at all. If there is a bug, I do not think it is affecting everyone. 

This may be related to [this](https://github.com/sveltia/sveltia-cms/issues/124)

**Comment by Because789** [comment]
No issues here, still working like a charm after my faux pas 😄

**Comment by kyoshino** [comment]
After #124, I’ve added a [simple check for a project/repository root directory](https://github.com/sveltia/sveltia-cms/commit/fd276b54760e8a5bff13492709542c8e9b9e8697). It just looks for the `.git` folder and shows an error message if not found. On Windows, you need to [change an option](https://support.microsoft.com/en-us/windows/view-hidden-files-and-folders-in-windows-97fbc472-c603-9d90-91d0-1166d1d9f4b5) to see the hidden folder on Explorer.

Have you started a repository (using the [`git init`](https://github.com/git-guides/git-init) command or a GUI like GitHub Desktop)? If not, please do so.

**Comment by sardarms** [comment]
I just added a `.git` folder and now its working! 

For your info, I did not start the repo with `git init`. I just copy files and start using the CMS. Previously it just worked. 

Thank you for your support 🙂

**Comment by kyoshino** [comment]
Got it!

**Comment by ddoan** [comment]
This breaks our project btw. We're a monorepo using mercurial.

**Comment by kyoshino** [comment]
Monorepos are not supported yet in Sveltia. And Mercurial won’t be supported since it’s a Git-based CMS.
