### ISSUE TITLE
PKCE authentication: content is not loaded and no error at all

### ISSUE THREAD

**Issue by josineto** [sveltia/sveltia-cms#136]
Using GitLab, with a private repository and CSP rules.

I've just configured PKCE authentication following [Decap CMS' docs on it](https://decapcms.org/docs/gitlab-backend/#client-side-pkce-authorization). First, I've got CSP errors due to two configurations not mentioned in Sveltia docs:

```
connect-src  https://status-api.hostedstatus.com
script-src   'unsafe-inline'
```

After adding them, I'm able to log in with GitLab, but **collections' content is not loaded** (just the configuration for the collections, populating the left sidebar) and **there's no error in browser console**.

The CMS works flawlessly when loaded with a local repository.

**Comment by kyoshino** [comment]
`https://status-api.hostedstatus.com` is mentioned in the doc, and I don’t think `unsafe-inline` is necessary (my client doesn’t have it.)

Are you using a self-hosted GitLab instance?

**Comment by kyoshino** [comment]
Just checked with my private test repo hosted on GitLab.com, and the content was loaded. Not sure what’s going on 🤔

**Comment by josineto** [comment]
> Are you using a self-hosted GitLab instance?

No, just a standard private gitlab.com repository.

Also, I've tested this in Firefox (125) and Chrome (123), with pretty much the same results, except in Chrome there's a "problems" message about discontinued use of `StorageType.persistent` when `navigator.storage` should be used instead. My site is builded by Hugo and hosted on Netlify. My GitLab account is protected by 2FA.

Below is the backend part of my configuration:

```yaml
backend:
  name: gitlab
  repo: <username>/<repository>
  auth_type: pkce
  app_id: <app-id>
```

In the first time I log in, after clicking "Authorize" in the screen below, the popup returns to the Sveltia login screen with the button "Sign In with GitLab". I then close the popup, and click "Sign In with GitLab" in the main window (which is also on the login screen). Then the screen below appears again, I click "Authorize" and then I log in, at the first collection but without any content. Everytime I log in, the screen below appears. Perhaps it's related, maybe the authentication is not being persisted?

![GitLab OAuth authorization screen](https://github.com/sveltia/sveltia-cms/assets/35090091/ac30ae9e-392c-4c62-bac1-b7bd575aa6a0)


I don't know if it's something related, but since the very first time I've used a static CMS (Netlify CMS at that time), I had to duplicate `config.yaml` both in `static/` and `static/admin/`, I don't know why. When I use Sveltia locally, it correctly reads from `static/admin/config.yaml`, but when on web it reads from `static/config.yaml`.

**Comment by kyoshino** [comment]
Tested with another site (actually the same but last time I connected it from localhost) hosted on Cloudflare Pages, but it also worked fine with PKCE.

Your API key is supposed to be stored in the browser’s local storage, named `sveltia-cms.user`. Can you find it? (under the Storage tab in Firefox DevTools, under the Application tab in Chrome DevTools)

> I don't know if it's something related, but since the very first time I've used a static CMS (Netlify CMS at that time), I had to duplicate `config.yaml` both in `static/` and `static/admin/`, I don't know why. When I use Sveltia locally, it correctly reads from `static/admin/config.yaml`, but when on web it reads from `static/config.yaml`.

I think it depends on the server or framework’s setting. Sometimes a trailing slash in the path is omitted, so when you access `/admin/`, you’ll be taken to `/admin`. The CMS tries to load the configuration file from the same directory, meaning `/config.yml` would be loaded instead of `/admin/config.yml`.

See https://github.com/decaporg/decap-cms/issues/7023

The solution is something like:
1. Open `/admin/#/` or `/admin/index.html`
2. Rename `index.html` to `cms.html` and open `/admin/cms` instead (I have done this for one of my clients)

**Comment by josineto** [comment]
> 2\. Rename `index.html` to `cms.html` and open `/admin/cms` instead (I have done this for one of my clients)

Thank you, I did this and it solved the conflict between configs.

> Your API key is supposed to be stored in the browser’s local storage, named `sveltia-cms.user`. Can you find it? (under the Storage tab in Firefox DevTools, under the Application tab in Chrome DevTools)

In local storage there are two keys:

- `sveltia-cms.user` with `backendName`, `token`, `name`, `login`, `email`, `avatarURL`, `profileURL` but no API key;
- `sveltia-cms.prefs`. with `apiKeys`, which is empty.

And as before, everytime I log in to CMS the GitLab screen above appears asking me to authorize.

Two new things:

1. I tried to create a new piece of content. It's perfectly created, and it appears in the CMS at its collection until I log out from CMS. If I log in again, the content I've just created doesn't appear anymore (and all other content doesn't appear either).
2. File collections' content is correctly loaded. So the problem only occurs with Folder collections.

**Comment by josineto** [comment]
(Listen, Sveltia CMS is fantastic, your work is great! I'd like to help more in this issue, but I don't know how)

**Comment by kyoshino** [comment]
Thanks for your kind words 🥰 I’d like to fix the issue anyway. Will dive into this further.

**Comment by kyoshino** [comment]
@josineto Would you mind inviting me to the private repository if it doesn’t contain confidential information? My GitLab account is [@koheiyoshino](https://gitlab.com/koheiyoshino).

**Comment by kyoshino** [comment]
Thanks, will check.

**Comment by kyoshino** [comment]
Looks like the project code is not available with the Guest role on private repo. Can you change my role to Reporter?

- https://gitlab.com/gitlab-org/gitlab-foss/-/issues/40624
- https://docs.gitlab.com/ee/user/permissions.html

> Repository: View project code
> On self-managed GitLab instances, users with the Guest role are able to perform this action only on public and internal projects (not on private projects). [External users](https://docs.gitlab.com/ee/administration/external_users.html) must be given explicit access (at least the Reporter role) even if the project is internal. Users with the Guest role on GitLab.com are only able to perform this action on public projects because internal visibility is not available.

**Comment by josineto** [comment]
@kyoshino done, you're now Reporter

**Comment by kyoshino** [comment]
Quick findings:

- If you are sign out of GitLab when you go through the authorization process, the popup window won’t close after you sign in and authorize the OAuth app. I have seen this issue before. If you manually close the popup, and click Sign In with GitLab, you should be able to sign in. I’ll try to find a solution.
- The content is not displayed due to [GitLab’s limit](https://docs.gitlab.com/ee/api/graphql/#limits) of 100 records per query. I’m fixing it now.

**Comment by kyoshino** [comment]
The fix shipped with [v0.26.4](https://github.com/sveltia/sveltia-cms/releases/tag/v0.26.4)! Can you please delete the local data base and try again? In Chrome, open DevTools, select the Application tab, select your repository name under IndxededDB, and Click Delete database. Then reload the page.

<img width="641" alt="Screenshot 2024-05-11 at 2 23 04 PM" src="https://github.com/sveltia/sveltia-cms/assets/2929505/07e1edb0-04eb-4868-8250-d000c2d57593">
﻿﻿

**Comment by josineto** [comment]
It works!!! Sorry for the delay, I've only managed to test it today, but it works and now I can say I'm **really** impressed with how responsive Sveltia CMS is, in terms of loading time of everything. It seems like I'm working completely local, it's really impressive! Your work is great, thank you!

**Comment by kyoshino** [comment]
No worries! Glad it works for you now! 👏🏼 

I forgot to mention that since GitLab only allows to retrieve 100 records (files) at once, loading the site data is slower than GitHub that doesn’t have such a limit. I think Sveltia CMS is overall still faster than Netlify/Decap CMS 😄

**Comment by josineto** [comment]
Yes, and also much faster than Static CMS (which uses React as well).

**Comment by kyoshino** [comment]
I know Static CMS but haven’t tried it myself yet. It’s a community maintenance fork of Netlify CMS. Just like Sveltia CMS, it was started before Decap CMS was announced. For some reason, they have [dropped the GraphQL support](https://www.staticcms.org/docs/decap-migration-guide#beta-features) and the bundle size is pretty huge (2.5 MB), so the performance isn’t great. They have better documentation than Netlify/Decap CMS though.

Sooner or later I’ll start working on Static CMS compatibility, including the [Key Value widget](https://www.staticcms.org/docs/widget-keyvalue), which effectively solves https://github.com/decaporg/decap-cms/issues/5489 🙂

**Comment by EKliptus** [comment]
Please I'm facing to a similar issue...
To test sveltia with astro (success with DecapCMS) I have use this template https://github.com/majesticooss/astro-starter and made only these changes : 
- change sveltia cms version to latest (now use @0.74.1)
- change config.yml for gitlab with pkce
```yaml
backend:
    name: gitlab
    branch: main
    repo: <owner/group/repo>
    auth_type: pkce
    app_id: <myGitlabAppId>
```
The project is only Static generated (no ssr).
I presume I don't need to deal with CSR ? I see https://status-api.hostedstatus.com request response 200 ok

I can auth with gitlab in the popup but when return to sveltiaCMS I get :

![Image](https://github.com/user-attachments/assets/46f533c9-c0ce-493e-8281-9cf7f6f970d7)

In network devtools I see request with my appId and no particular errors.
Like say here https://github.com/sveltia/sveltia-cms/issues/136#issuecomment-2097340293


> In local storage there are two keys:
>     * `sveltia-cms.user` with `backendName`, `token`, `name`, `login`, `email`, `avatarURL`, `profileURL` but no API key;
>     * `sveltia-cms.prefs`. with `apiKeys`, which is empty.

I have the same empty objects...

Any idea for my similar case ? Thanks you !

**Comment by EKliptus** [comment]
Found fix for `invalid_client` response by gitlab :
On the created CMS gitlab application settings : uncheck "Confidential" to disable client secret.
