### ISSUE TITLE
File System Access API Chrome Android Not Work

### ISSUE THREAD

**Issue by husenlovedisney** [sveltia/sveltia-cms#14]
OS : Android 13
Browser : Chrome 112.0.5615.135

When I use the local Git repository and open the admin page in Chrome it shows like the image below.
![IMG_20230513_181203](https://github.com/sveltia/sveltia-cms/assets/122751959/ace8d27a-1cfa-4b8e-b549-8aafe978b426)
I found this [page](https://bugs.chromium.org/p/chromium/issues/detail?id=1011535) which shows that there is a "File System Access API" bug on Chrome Android

Thank You🙏

**Comment by kyoshino** [comment]
Thanks for reporting this, but given that it’s a Chrome bug, I have nothing to do here. Also, mobile support (responsive design) is not planned with Sveltia CMS due to limited use cases. Please use Chrome on your desktop instead. 🙏🏻
