### ISSUE TITLE
Follow field ordering of config when writing files

### ISSUE THREAD

**Issue by josineto** [sveltia/sveltia-cms#144]
The field ordering when writing the files is completely different from the ordering set in `config.yml`. It would be friendlier to developers if files were written following the ordering set in configuration.

I know probably this means changing the internal data structure (from sets to arrays), but perhaps you may apply that ordering only when writing, to speed up the process...

**Comment by kyoshino** [comment]
It’s on my todo list. Netlify/Decap CMS has the same issue (particularly with JSON):

- https://github.com/decaporg/decap-cms/issues/6759
- https://github.com/decaporg/decap-cms/issues/6901

**Comment by kyoshino** [comment]
Just shipped [v0.28.0](https://github.com/sveltia/sveltia-cms/releases/tag/v0.28.0) with the fix!
