### ISSUE TITLE
CMS on mount, not respecting localstorage

### ISSUE THREAD

**Issue by jamieRowen-mediacom** [sveltia/sveltia-cms#145]
I will preface this with I am not a front end dev by any means, so if this question is silly please let me know and apologies.

If I look at https://github.com/sveltia/sveltia-cms/blob/main/src/lib/services/user.js#L68 and https://github.com/sveltia/sveltia-cms/blob/c007deb89cb68d71198b1e3d05f55adc268c3370/src/lib/components/entrance/sign-in.svelte#L16 my, possibly naive, expectation would be that if "decap-cms-user" is in localStorage that would be picked up and login would be automatic but I don't find this to be the case. 

Am I misunderstanding something here?

Attached is screen shot of local storage and login page

<img width="1720" alt="sveltia" src="https://github.com/sveltia/sveltia-cms/assets/114474007/bd8c9af3-1844-49fb-9415-25f66b1bf490">

**Comment by kyoshino** [comment]
No worries! Sveltia CMS picks up `decap-cms-user` but a token is required to sign in.

And oh, it seems you’re using a local server. Then you can [work with a local repository](https://github.com/sveltia/sveltia-cms?tab=readme-ov-file#working-with-a-local-git-repository) by opening `http://localhost:4321` instead of `http://127.0.0.1:4321`.

**Comment by jamieRowen-mediacom** [comment]
> No worries! Sveltia CMS picks up `decap-cms-user` but a token is required to sign in.
> 
> And oh, it seems you’re using a local server. Then you can [work with a local repository](https://github.com/sveltia/sveltia-cms?tab=readme-ov-file#working-with-a-local-git-repository) by opening `http://localhost:4321` instead of `http://127.0.0.1:4321`.

thanks for the quick response. I can get the login sorted by re-instating the token.

I am aware of the local host and local repo option, thank you however, my use case is such that I don't want to run against the local copy of the repo, I want to roll the CMS into another tool for my users who may run locally, but have a choice of repos that they want to interact with.
