### ISSUE TITLE
The backup popup bug

### ISSUE THREAD

**Issue by CarloBu** [sveltia/sveltia-cms#148]
I found the bug in the backup popup logic. It shows up even when the changes are saved. It looks like there is no comparing step with the local backup data of the field and the field data stored at md/yaml/json.

to recreate:
go to the created collection field, make changes, save, exit, then open the same field again, and the popup shows up to restore the data, that is already saved. At least this bug is happening in the local environment, I haven't tested it at the cdn yet.

https://github.com/sveltia/sveltia-cms/assets/145860771/a58e97a2-5581-4aea-a1cc-3c4625a2e877

**Comment by kyoshino** [comment]
The backup is deleted when an entry is saved. Will check why the popup still appears.

**Comment by CarloBu** [comment]
Oh ok, maybe this is an issue with my environment, I use default Chrome in this situation.

**Comment by kyoshino** [comment]
Could reproduce the issue with a new entry 😅 Fix on the way.

**Comment by kyoshino** [comment]
Fixed in [v0.29.1](https://github.com/sveltia/sveltia-cms/releases/tag/v0.29.1) 🙇🏼
