### ISSUE TITLE
Cannot read properties of undefined (reading 'i18n')  

### ISSUE THREAD

**Issue by privatemaker** [sveltia/sveltia-cms#15]
Due to my last bug finding success- after unsuccessfully fiddling with configs, I decided to open this issue. Hugo is my SSG.

![sveltia-i18n-error](https://github.com/sveltia/sveltia-cms/assets/49612519/46e9b527-dfad-444a-b0c2-e59422a58f8b)

The bug is present with the following configs: 

```
# Path
content/en/collection/
content/english/collection/

# Config
i18n:
  structure: multiple_folders
```

```
# Path
content.en/my-collection/

# Config
i18n:
  structure: single_file
```

```
# Path
content/my-collection/file.en.md

# Config
i18n:
  structure: multiple_files
```

My i18n exists `themes/my-theme/i18n/` but this should not matter as I understand it, but I did create a `i18n/` directory in the root.

The following view works fine:

- http://localhost:1313/admin/#/collections/my-collection

The bug shows up in the log when clicking on an entry of `New` button, or loaded via URL.

I am only testing this with local repo file system access, not Github.

**Comment by kyoshino** [comment]
Thanks for reporting! I think I hit the same issue when I accidentally opened an invalid collection path (because I’m testing with multiple client configurations locally.) Will sort it out.

**Comment by kyoshino** [comment]
@privatemaker Can you verify the fix I just deployed? Thanks!

**Comment by privatemaker** [comment]
Yep. Fixed. Thanks 😄
