### ISSUE TITLE
Error with required list widget when there are no fields

### ISSUE THREAD

**Issue by josineto** [sveltia/sveltia-cms#152]
Since 0.31.1, a required 'simple' list field (i.e. with no internal fields, a list of strings) throws an error (as a red notification) when trying to save a collection item. And the number of errors is equal to the number of items in the field.

So, for example, if I enter "category1, category2, category3" in a field like the one configured below, when I try to save it a notification shows "3 fields have an error. Please correct them to save the entry." If the field has `i18n: true` and there are other three items in the translated field, the message is "6 fields have an error (...)" and so on. But the field that throws the error is not marked as red (as typically happens when a field has an error).

The problem doesn't occur if `required: false`.

The field is configured like below:

```yaml
- label:  Categorias
  name:   categories
  widget: list
  i18n:   true
  required: true
```

**Comment by kyoshino** [comment]
Thanks for the heads-up! Will fix it now.

**Comment by josineto** [comment]
Thank you!
