### ISSUE TITLE
uuid widget : uuid don't change when "duplicate"

### ISSUE THREAD

**Issue by QaldeK** [sveltia/sveltia-cms#157]
Hi,
When i click to "duplicate" a post, all fields values are duplicate, including the uuid. It seems to me that it should be regenerated

**Comment by kyoshino** [comment]
Yup, will fix! 😅

**Comment by QaldeK** [comment]
Thanks !

**Comment by kyoshino** [comment]
The fix landed in [v0.34.2](https://github.com/sveltia/sveltia-cms/releases/tag/v0.34.2)!
