### ISSUE TITLE
getting an error trying to save edits in production...

### ISSUE THREAD

**Issue by rchrdnsh** [sveltia/sveltia-cms#158]
Getting the following error dialog when trying to save an edit to a collection entry on the live site:

<img width="719" alt="Screenshot 2024-06-06 at 1 30 51 PM" src="https://github.com/sveltia/sveltia-cms/assets/7884263/c52fc60f-8bf2-4f46-8db6-04b093082609">

It happens in production for multiple people...

it seems to happen for all collections

Here are the errors in the console:

<img width="578" alt="Screenshot 2024-06-06 at 1 35 24 PM" src="https://github.com/sveltia/sveltia-cms/assets/7884263/a3162039-a029-4c89-aadf-5d058779f04c">

and expanded:

<img width="577" alt="Screenshot 2024-06-06 at 1 36 14 PM" src="https://github.com/sveltia/sveltia-cms/assets/7884263/1ffabee1-5b7c-4c98-af7a-e5874a0f47f2">

I hope that helps :-)

**Comment by kyoshino** [comment]
Hmm, my quick test doesn’t reproduce the error. Do you see any error in the Network tab? A normal response would look like this:

<img width="897" alt="image" src="https://github.com/sveltia/sveltia-cms/assets/2929505/72c03624-3338-4076-8d00-90b1604adbfb">

**Comment by rchrdnsh** [comment]
this is the network info I am getting when I click save...

There are two `graphql`'s that are created...

The first one is this:

<img width="1798" alt="Screenshot 2024-06-06 at 2 35 42 PM" src="https://github.com/sveltia/sveltia-cms/assets/7884263/ffbea988-f659-40ff-b989-cd058f6756be">

and the second one is this:

<img width="1796" alt="Screenshot 2024-06-06 at 2 34 17 PM" src="https://github.com/sveltia/sveltia-cms/assets/7884263/18aaf94f-6ef8-44a6-aa4c-47425c866555">

I do nto really understand them myself, but hopefully this helps :-)

**Comment by kyoshino** [comment]
Can I see the Preview tab next to Payload?

**Comment by rchrdnsh** [comment]
aha!!! under the preview tab I figured out i somehow had the wrong repo name...i fixed it and it worked!!! schweet :-) Thank you for guiding me

**Comment by kyoshino** [comment]
This is interesting, actually. If the config file has a wrong repo name, you should get an error while fetching data at startup. Not sure why it’s not the case 🤔
