### ISSUE TITLE
loading config returns 404 when site is non-root of domain

### ISSUE THREAD

**Issue by privatemaker** [sveltia/sveltia-cms#16]
When loading Sveltia CMS `v.0.3.5` from the following path:

```
https://example.org/my-actual-site/admin/
```

It returns `404` for the `config.yml` as it tries to load from: 

```
https://example.org/admin/
```

**Comment by kyoshino** [comment]
Looks like the current configuration path is written in an absolute path `/admin/config.yml`. I’ll change it to relative.

In the meantime, you should be able to work around the issue by [specifying the config path in the HTML file](https://decapcms.org/docs/configuration-options/#configuration-file) 🙂

**Comment by privatemaker** [comment]
Also fixed!!

**Comment by kyoshino** [comment]
Thanks for the verification! 🙌
