### ISSUE TITLE
Missing Github Login Button on Login Page in Firefox

### ISSUE THREAD

**Issue by MSalah73** [sveltia/sveltia-cms#170]
I've encountered a bug while trying to login to the admin panel via github using firefox. The login button is missing, and the page just says "signing in...". Everything works as intended when switching to a chromium based browsers.

![Screenshot 2024-06-22 144045](https://github.com/sveltia/sveltia-cms/assets/27312622/68c653bb-60a4-4803-838b-f6d6a674ca4b)

**Comment by kyoshino** [comment]
I’ve tested with a couple of instances but haven’t been able to reproduce the issue. Do you see any error in the browser’s console?

**Comment by MSalah73** [comment]
Yes, its a BridgeTimeout error - throw.ts line 4
[
![Screenshot 2024-06-23 095712](https://github.com/sveltia/sveltia-cms/assets/27312622/94591720-1957-46d1-9bcf-ec28d424f986)
](url)

**Comment by kyoshino** [comment]
That’s weird, it’s not an error of Sveltia CMS. There is no TypeScript code here. A quick search for `BridgeTimeout` finds an IBM application. Or perhaps do you use any browser extension?

**Comment by kyoshino** [comment]
https://github.com/ProtonMail/WebClients/blob/main/applications/pass-extension/src/app/content/bridge/message.ts#L53
https://github.com/ProtonMail/WebClients/blob/main/packages/pass/utils/fp/throw.ts

Do you use the Proton Pass extension?

**Comment by MSalah73** [comment]
Yes, but it seems that the problem wasn't Proton. I deleted all the cache, and now it seems to be working. That was shortsighted on my part.

**Comment by kyoshino** [comment]
Still not sure how that situation could have happened, but glad the problem has been solved!
