### ISSUE TITLE
Suggestion: simple list field on summary

### ISSUE THREAD

**Issue by josineto** [sveltia/sveltia-cms#174]
Hi, I'd like to include a simple list field within a summary. Maybe a function like `{{ concat(fields.list) }}`?

**Comment by kyoshino** [comment]
How would the config look like?

**Comment by kyoshino** [comment]
The fix shipped with [v0.35.0](https://github.com/sveltia/sveltia-cms/releases/tag/v0.35.0) 🚢

**Comment by josineto** [comment]
Thank you!

**Comment by josineto** [comment]
> How would the config look like?

It perfectly works, now that I've tested it. Sorry for not having answered in time, this week was insane for me.
