### ISSUE TITLE
Local backend breaks and gets notification when remote backend "is experiencing a major incident"

### ISSUE THREAD

**Issue by josineto** [sveltia/sveltia-cms#175]
As I write this issue, GitLab (my remote backend) [has a specific problem](https://status.gitlab.com/), and thus Sveltia CMS warns me that "GitLab is experiencing a major incident" (which is very nice, by the way). As I'm working on a local server, Sveltia CMS offered me to use local or remote backend (as of v0.35.0). But when I connect to local, the same notification appears: "Local Repository is experiencing (...)", with a link to `about:blank`. Worse: I can't edit any item of any collection, be it file or folder collection (although I can change between collections, trying to enter the editor does nothing, and JS Console is empty).

![Screen with wrong notification](https://github.com/sveltia/sveltia-cms/assets/35090091/9ddeba0f-07d4-40c8-a92d-6209975a074e)

**Comment by josineto** [comment]
(Sorry, I was eager to test v0.35.0, but (perhaps luckily) faced this problem...)

**Comment by kyoshino** [comment]
Thanks for catching this. Will fix.

**Comment by kyoshino** [comment]
> Worse: I can't edit any item of any collection, be it file or folder collection (although I can change between collections, trying to enter the editor does nothing, and JS Console is empty).

Hmm, I’m not able to reproduce the problem. Sveltia CMS could disable editing functionality in case of a major incident, but I haven’t implement it; instead, it just shows a notification as you see. Not sure why this happens 🤔

**Comment by kyoshino** [comment]
The incident notification is now hidden with the local backend as of [v0.35.1](https://github.com/sveltia/sveltia-cms/releases/tag/v0.35.1). Let me know if the editing issue still happens.

**Comment by josineto** [comment]
The editing issue has gone as well. Sorry for not having more evidences of it, the console was empty when it happened. Anyway, thank you for the fast correction!

**Comment by kyoshino** [comment]
No worries, thanks for verifying the fix!
