### ISSUE TITLE
`widget: relation` with `multiple:true` wrong order of elements in UI

### ISSUE THREAD

**Issue by frankbits** [sveltia/sveltia-cms#18]
When you use the widget `relation` with the option `multiple` enabled, the selected elements get displayed in alphabetical order in the CMS-UI (Editor & Preview).
They get saved in the corresponding file correctly sorted by insert-order

**Comment by kyoshino** [comment]
I think sorting is needed only for the dropdown list. Will fix.

**Comment by kyoshino** [comment]
#18, #19 and #20 are now fixed in the latest version 0.3.7. Thanks for your patience!
