### ISSUE TITLE
Float gets truncated in widget "number"

### ISSUE THREAD

**Issue by henriksommerfeld** [sveltia/sveltia-cms#181]
I have a field defined like this in [my config.yml](https://github.com/henriksommerfeld/food-sveltekit/blob/main/static/admin/config.yml):
```
{
  label: 'Mängd',
  name: 'ingredientamount',
  widget: 'number',
  valueType: 'float',
  min: 0,
  hint: 'Ange 0 om du inte vill visa någon mängd, ex. "salt"'
},
```

When a value is set to `1.5` in markdown, it is parsed and presented as `1` in the editor. Even if I enter `1.5` again in the editor, it writes `1` back to the markdown file. This config file is migrated from NetlifyCMS, but I don't see a reason for floats to be truncated to ints, right?

I'm using the latest version through https://unpkg.com/@sveltia/cms/dist/sveltia-cms.js.

**Comment by kyoshino** [comment]
Will check@
