### ISSUE TITLE
Cannot use repositories with more than two path elements

### ISSUE THREAD

**Issue by paulbdavis** [sveltia/sveltia-cms#183]
From the PR I submitted: #182 

> The current check for the repo configuration enforces the github style `username/repo`, but it's not uncommon for self hosted gitlab instances to use multiple levels there (i.e. `team/project/component`)

**Comment by kyoshino** [comment]
Thanks for the heads-up! Fixed in [v0.36.3](https://github.com/sveltia/sveltia-cms/releases/tag/v0.36.3).
