### ISSUE TITLE
UI not loading as part of Hugo module

### ISSUE THREAD

**Issue by moookino** [sveltia/sveltia-cms#186]
Hi,

Can you help to troubleshoot what's wrong with using of Sveltia cms as hugo module?
I created an issue https://github.com/privatemaker/headless-cms/issues/2 but I'm not sure if that's hugo module issue or sveltia issue

**Comment by kyoshino** [comment]
Please discuss in https://github.com/privatemaker/headless-cms/issues/2, and I’m happy to help if it’s a Sveltia CMS issue.

**Comment by richtong** [comment]
Yes, privatemaker doesn't seem to be responding on how to fix this. at least from august to October :-). Looking at his partial, I'm no go or hugo expect, but besides a lot of duplicated code in the partial, it looks like it is loading the correct sveltia.js file

https://github.com/privatemaker/headless-cms/blob/main/layouts/_default/headless-cms.html

I confess i don't understand the yaml file that is also there https://github.com/privatemaker/headless-cms/blob/main/layouts/_default/index.headlesscmsconfig.yaml
