### ISSUE TITLE
Missing entry in `.gitignore` (`.pnpm-store`).

### ISSUE THREAD

**Issue by tysonclugg** [sveltia/sveltia-cms#188]
As per https://github.com/sveltia/sveltia-cms/pull/187/commits/baff945d0e3b5762049b02becf7c68034d1e527f and the associated note in PR #187, the `.pnpm-store` directory should be excluded from source control.

**Comment by kyoshino** [comment]
I don’t think it’s necessary. pnpm store is [not project-specific](https://stackoverflow.com/questions/55403775/how-to-get-pnpm-store-directory) (it’s an advantage of pnpm) and is not included in typical `.gitignore`. Feel free to add it your fork if needed.

**Comment by tysonclugg** [comment]
This is an artefact of how pnpm works, they have an open discussion on the matter:
https://github.com/orgs/pnpm/discussions/3651

This issue can be closed, thanks. 🙂
