### ISSUE TITLE
"String templates" don't work with nested fields (+ wildcard) in `display_fields` and `value_field`

### ISSUE THREAD

**Issue by frankbits** [sveltia/sveltia-cms#19]
In `widget: relation` string templates (`{{field}}`) only work in `display_fields` on not nested fields (+ wildcard).
If it is used with a nested field (e.g. `{{sections.*.id}}`) no content is visible in the editor-dropdown-selector

**Comment by frankbits** [comment]
same in `value_field`. Would like to save the page route `{{route}}` together with `{{sections.*.id}}`...

**Comment by kyoshino** [comment]
Oh yeah, that’s a missing use case! Will take care of it.

**Comment by frankbits** [comment]
`"{{route}}#{{sections.*.id}}"` still not working.
gets saved with the `{{}}` (`{{/}}#{{about-me}}`)
