### ISSUE TITLE
Unable to unselect relation widget with multiple: false & required: false

### ISSUE THREAD

**Issue by AntoineBx** [sveltia/sveltia-cms#191]
Hello, first of all thanks for sveltia cms, it is amazing!
Now i am maybe missing an option in the doc. But i try to unselect a relation widget with mutiple: false & required: false, but i cannot. I didn't try to do the same with decap so i coun't tell you if it is a sveltia only problem. Thanks in advance for your help

- label: 'nav primary'
                name: 'primary'
                widget: 'relation'
                i18n: true
                collection: 'pages'
                required: false
                multiple: false
                search_fields: ['page_id']
                value_field: 'page_id'
                display_fields: ['page_id']

**Comment by kyoshino** [comment]
Thanks for reporting the issue. Will check.

**Comment by kyoshino** [comment]
Just shipped [v0.37.1](https://github.com/sveltia/sveltia-cms/releases/tag/v0.37.1) to solve the problem. Now you’ll see the “(None)” option that allows you to deselect a defined option.

### A few options

<img width="527" alt="image" src="https://github.com/user-attachments/assets/56aa1215-6da9-4da9-b318-167f9324f6ee">

### More options

<img width="527" alt="image" src="https://github.com/user-attachments/assets/e6195923-868a-40d4-b0af-2f063b9d0408">
