### ISSUE TITLE
regression 0.37.1 Markdown content disappear

### ISSUE THREAD

**Issue by AntoineBx** [sveltia/sveltia-cms#193]
In 0.37.0 it's good
![Capture d'écran 2024-08-25 170236](https://github.com/user-attachments/assets/d9ae1521-5a13-4d06-9ed2-99f2d547fb33)
But if i switch to 0.37.1
![Capture d'écran 2024-08-25 170801](https://github.com/user-attachments/assets/84f46f66-6b65-419e-95d7-dd1549001816)
And if i click on the body input, it delete the value in the preview
I tried creating Markdown field with different name, it doesn't work either. It doesn't seem like it is related to the body field only but all markdown field 

Maybe it is the change you made in  src/lib/components/contents/details/widgets/markdown/index.js ?

**Comment by kyoshino** [comment]
Just shipped [v0.37.2](https://github.com/sveltia/sveltia-cms/releases/tag/v0.37.2) to solve the problem. Sorry for the inconvenience!
