### ISSUE TITLE
Publish source maps

### ISSUE THREAD

**Issue by devurandom** [sveltia/sveltia-cms#197]
My page has `<script src="https://unpkg.com/@sveltia/cms/dist/sveltia-cms.js" type="module"></script>`, cf. https://github.com/devurandom/sveltia-cms-eleventy-base-blog/blob/main/admin/index.html.  I get `Uncaught (in promise) TypeError: d.trim is not a function` in `update` at `https://unpkg.com/@sveltia/cms/dist/sveltia-cms.js:442`.  Sadly the source is illegible (`[...]b(d?.trim()??""),t.$$.dirty&16[...]`) and Firefox 130's debugger says "No source map found".

Is there something I am missing to do so that Firefox would find Sveltia's source map, or is it just not published?  If the latter, would it be possible to publish it?

**Comment by kyoshino** [comment]
Thanks for the heads-up! The source map is not published yet. I’ll make it happen.

How can I reproduce the issue? Can you provide your configuration (with sensitive info removed) if possible?

**Comment by devurandom** [comment]
> How can I reproduce the issue? Can you provide your configuration (with sensitive info removed) if possible?

I don't know yet.  It seems to affect only specific entries in one collection.  I'll report a separate issue on the `trim is not a function` error once I have the source map and can debug it a bit further.

**Comment by kyoshino** [comment]
The error comes from:

https://github.com/sveltia/sveltia-cms/blob/d40e733b7468d16b165154cce4eed97aa7c0088d/src/lib/components/contents/details/widgets/string/string-editor.svelte#L101

**Comment by devurandom** [comment]
Firefox now recognises that there is a source map, but fails to load it: `Source Map Error: NetworkError when attempting to fetch resource.`  The "network" tab of the developer console does not show anything related and `view-source:https://unpkg.com/@sveltia/cms@0.38.4/dist/sveltia-cms.js.map` ("Open the Source Map file in a new tab") loads fine.  Any idea what the issue might be?

**Comment by devurandom** [comment]
> I think my first guess was right, assuming you’re pointing to the right location (`[...]b(d?.trim()??""),t.$$.dirty&16[...]`).
> 
> Still not sure exactly how the error would happen, but for example, if the value comes from outside Sveltia CMS and the type is an array, boolean, number, etc. for some reason, the code would fail as it only took into account a string, `null` or `undefined`.

The YAML front matter of this collection entry contains `location: 0210` (the one that worked does not contain such entry in the front matter).  The `config.yaml` specifies `{ label: "Location", name: "location", widget: "string", hint: "[...]", required: false }` for this collection.  With Sveltia v0.38.4 the "Location" field is shown empty in the UI, for the collection entry that previously did not render / showed as a blank page.

I guess the line in the front matter should be `location: "0210"` to prevent parsing it as a number?

**Comment by kyoshino** [comment]
Yeah, Chrome can load it but Firefox fails. Maybe it’s a bug in Firefox. (Mozilla is my former company and current client, btw. I’m a long-time Firefox user) 😅 

Ohh, so the culprit is the YAML library storing the numeric value as a number. Will figure out how to work around the issue.

In the meantime, you can use a [collection configuration](https://github.com/sveltia/sveltia-cms?tab=readme-ov-file#better-data-output) to make sure the value is saved as a string:

> String values in YAML files can be quoted with the new `yaml_quote: true` option for a collection, mainly for framework compatibility

**Comment by devurandom** [comment]
> Ohh, so the culprit is the YAML library storing the numeric value as a number. Will figure out how to work around the issue.

Maybe you can transform the input according to the `widget` specified in `config.yml`, before processing it further?

I used the `string` widget, because I don't want Sveltia to interpret this in any way, i.e. I want it treat the field as an opaque string.  E.g. I do not want the leading `0` to be stripped, or for this to be interpreted as an octal number.  In my particular case whitespace trimming should be fine, but I did not even expect Sveltia to do that.

**Comment by devurandom** [comment]
> By any chance, the value came from somewhere else?

I think I wrote those files by hand, more than a year ago, since Sveltia was not yet as advanced as it is today.

**Comment by kyoshino** [comment]
Ah okay. Then you can manually edit the value, and next time Sveltia CMS saves the entry, it should be saved as a quoted string 🙂
