### ISSUE TITLE
Uncaught Error: effect_update_depth_exceeded

### ISSUE THREAD

**Issue by bmackinney** [sveltia/sveltia-cms#199]
Steps to reproduce:

1. clone https://github.com/basa-casa/hugo-admin/tree/sveltia
2. run `hugo server` and open http://localhost:1314/admin/#/collections/admin-pages
3. Use local repository - select hugo-admin directory.
4. JS error appears in console.
5. Click on an entry - the URL changes but the livereload server does not finish.

**Comment by kyoshino** [comment]
Thanks for reporting the issue! It seems like a fallout from the Svelte 5 migration. Will check.

**Comment by kyoshino** [comment]
Just shipped [v0.39.2](https://github.com/sveltia/sveltia-cms/releases/tag/v0.39.2) with the [fix](https://github.com/sveltia/sveltia-cms/commit/45770ca6634314ca9ee80e0f19d93f479cafa00a) 🙇🏼
