### ISSUE TITLE
key value widget

### ISSUE THREAD

**Issue by bmackinney** [sveltia/sveltia-cms#200]
[I just liked a comment you made about planning staticcms.org features].(https://github.com/sveltia/sveltia-cms/issues/136#issuecomment-2111391466)

The key value widget would solve a few problems for my hugo config editor.

**Comment by kyoshino** [comment]
I’ve just realized that you are the reporter of https://github.com/decaporg/decap-cms/issues/5489! I was planning to implement the KeyValue widget after the Sveltia 1.0 release, but given the fate of Static CMS, I’ll bring the plan forward as early as next month. It’s probably not difficult. 🙂

**Comment by adriandpdev** [comment]
hi @kyoshino, Do you have any progress on this new feature? It is very interesting for me too

**Comment by kyoshino** [comment]
Apparently some Static CMS users are migrating to Sveltia CMS, so I’ll be working on it very soon! The next minor release will ship with the new widget.

**Comment by adriandpdev** [comment]
Yes, i migrate to sveltia cms this weeks and feels good. Thank you very much for the development. Although now I will open a case because it is not responding correctly.

**Comment by kyoshino** [comment]
The KeyValue widget is now in [v0.50.0](https://github.com/sveltia/sveltia-cms/releases/tag/v0.50.0) 🎉
