### ISSUE TITLE
One folder cannot be used for multiple collections (with filter applied)

### ISSUE THREAD

**Issue by bmackinney** [sveltia/sveltia-cms#201]
steps to reproduce:

1. checkout the sveltia branch of https://github.com/basa-casa/hugo-admin
1. hugo server
1. http://localhost:1313/admin/collections does not display any folder collections (there are a lot) but does display files collections (there are two). both collections have the same filter field but different values (folder or files). 
 
```
filter: 
  field: collection_type
  value: folder
```
After changing collections all from "folder" to files, each displays in the files collections entries. 

Field collections at http://localhost:1313/admin/fields also do not function.

**Comment by kyoshino** [comment]
Looks like the filter itself is fine, but the entry listing is confused because `folder: data/scms/collections` is used for both collections. Fixing.

**Comment by kyoshino** [comment]
Let me think about how to fix this... Having a many-to-many relationship will affect many parts of the app. 😅 

I’m shipping the fixes for #202 and other issues first.

**Comment by kyoshino** [comment]
I’m also checking for other bugs with your setup. One thing I’ve noticed is, on `http://localhost:1313/admin/#/collections/admin-pages/entries/collections`, the Add menu checkbox doesn’t work as expected.

**Comment by kyoshino** [comment]
I have made progress. It’s a major refactoring, so I’ll make sure everything works well.

![localhost_1313_admin_collections_](https://github.com/user-attachments/assets/eb9a43e7-907a-4bb8-bf13-2b0f0a60c74c)

**Comment by kyoshino** [comment]
The fix landed in [v0.39.9](https://github.com/sveltia/sveltia-cms/releases/tag/v0.39.9). I’ll work on remaining hugo-admin compatibility issues later this week.
