### ISSUE TITLE
CMS takes whole window, even with `<div id="nc-root">`

### ISSUE THREAD

**Issue by bmackinney** [sveltia/sveltia-cms#202]
https://decapcms.org/docs/custom-mounting/#gatsby-focus-wrapper indicates I can display a menu in the html above the CMS, but the CMS still covers the whole page.
https://github.com/decaporg/decap-cms/issues/1740

**Comment by kyoshino** [comment]
You should be able to do this, but make sure `<div id="nc-root">` actually has a space to render the CMS (with `position:absolute`, inside fiexbox, etc.) That said, I’m adding a calculated style to unstyled `<div id="nc-root">`.

![image](https://github.com/user-attachments/assets/44a5d480-9c48-40df-be45-1c736def1877)
 
<img width="472" alt="Screenshot 2024-09-16 at 12 46 09 AM" src="https://github.com/user-attachments/assets/d6ab50c7-e448-44f8-9609-8abf57b01d9c">

Also I’m fixing other issues:

- `<div id="nc-root">` is ignored if it appears after the CMS `<script>`
- A redundant `window.CMS.init()` (found in your project) initializes the CMS twice

**Comment by kyoshino** [comment]
The fixes shipped with [v0.39.4](https://github.com/sveltia/sveltia-cms/releases/tag/v0.39.4).
