### ISSUE TITLE
Cursor jumps back to beginning of md field when holding down backspace.

### ISSUE THREAD

**Issue by bmackinney** [sveltia/sveltia-cms#208]

**Comment by bmackinney** [comment]
Also when tapping backspace more than once in succession.

**Comment by kyoshino** [comment]
Perhaps a bug or design of the Lexical editor. I’ll test with the latest version of Lexical released yesterday.

**Comment by kyoshino** [comment]
Fixed in [v0.39.13](https://github.com/sveltia/sveltia-cms/releases/tag/v0.39.13).
