### ISSUE TITLE
Stuck at signing in....

### ISSUE THREAD

**Issue by bmackinney** [sveltia/sveltia-cms#209]
Workaround: hugo server -p=1314 or incognito window, deleting some app data eventually unstuck it. Makes me think it's probably cache-related?

**Comment by kyoshino** [comment]
Do you see any errors in the console?

**Comment by bmackinney** [comment]
Nothing in the console, no. I'll look closer if it happens again.

**Comment by kyoshino** [comment]
I’m closing this, but please feel free to reopen it if you still see the problem.

**Comment by TimJJTing** [comment]
@bmackinney did you just migrate from netlify-cms or decap-cms? can you pass through with incognito mode? if so, you might want to clean everything in localstorage and try again
