### ISSUE TITLE
Folder collection `path: ""` returns no entries

### ISSUE THREAD

**Issue by bmackinney** [sveltia/sveltia-cms#216]

**Comment by kyoshino** [comment]
`path: ""` means the root folder?

**Comment by bmackinney** [comment]
It should be relative to the folder value, so `path: ""` should do nothing?

**Comment by kyoshino** [comment]
Ah, I see, it’s a relative path for sure.

**Comment by kyoshino** [comment]
Fixed in [v0.39.17](https://github.com/sveltia/sveltia-cms/releases/tag/v0.39.17) 🙇🏼
