### ISSUE TITLE
Relation widget `value_field` with string templates gets saved with brackets

### ISSUE THREAD

**Issue by frankbits** [sveltia/sveltia-cms#23]
> `"{{route}}#{{sections.*.id}}"` still not working.
> gets saved with the `{{}}` (`{{/}}#{{about-me}}`)

_Originally posted by @frankbits in https://github.com/sveltia/sveltia-cms/issues/19#issuecomment-1574907915_

This also breaks how the current data is shown in the sveltia-UI after reopening the saved collection

**Comment by kyoshino** [comment]
Will see.

**Comment by kyoshino** [comment]
Well, I didn’t include the template support for `value_field` because it’s not mentioned in the [Relation widget document](https://decapcms.org/docs/widgets/#relation) other than `{{slug}}`, but I’ll see if it can be done.

**Comment by frankbits** [comment]
Ah ok... but for my use-case it's needed there... thanks for looking into it

**Comment by frankbits** [comment]
Isn't only the `{{}}` missing in the `values`-replace?

src/lib/components/contents/details/widgets/relation/helper.js:92
```
labels[valueIndex] = labels[valueIndex].replaceAll(`{{${key}.${k}}}`, v);
values[valueIndex] = values[valueIndex].replaceAll(`${key}.${k}`, v);
```

**Comment by frankbits** [comment]
I mean, the String-Template in value-field does get replace correctly apart from the `{{}}`, so it is already mostly included...

**Comment by kyoshino** [comment]
Deployed the fix 🚢

**Comment by kyoshino** [comment]
Thanks for testing!
