### ISSUE TITLE
Vitepress support

### ISSUE THREAD

**Issue by Niek** [sveltia/sveltia-cms#230]
Hello, did anyone manage to get sveltia-cms working properly with Vitepress? I found the following issues so far:
* Collections does not support the root folder `.` - you need to move all .md files in a separate folder (not the biggest issue, still annoying)
* All .md files in a collection need to have empty frontmatter at the start of the file, otherwise an error is thrown that `yaml-frontmatter` cannot be parsed (sounds like a bug to me)
* Since vitepress usually doesn't need any frontmatter, it would be nice if the title could be parsed from the Markdown header - any chance this is possible?

**Comment by kyoshino** [comment]
I’ll check this out sometime this week or next.

**Comment by naton** [comment]
I've gotten it to work pretty well now, thanks to your suggestions above. However, there seems to be issues with code like ` ```html [Tab one] ` which adds a line-break before the `[` character (which then breaks the code-group:s in VitePress).

Is there a way to configure away this? Or, alternatively, a way to only support the Markdown editor (which seems less prone to "correct" my texts)

**Comment by kyoshino** [comment]
Done in 461136df03f07c936dc2e8b3dee990315cd94106, 4d3ea514fb2dd6405b8484fb88b43118e2ef9d30, 69604cc5e2840f211443cef7f50368014c750848, 03431d3646122d1b4ddcb2681a3f81933d08bf51, 6e3cca51ff3613b77be6b242a5b6e2f281e953d6.

**Comment by kyoshino** [comment]
Shipped [v0.47.0](https://github.com/sveltia/sveltia-cms/releases/tag/v0.47.0) with VitePress support 🚢

**Comment by Niek** [comment]
Amazing stuff, thanks a lot @kyoshino!
