### ISSUE TITLE
Npm import, no longer works for me on 0.4

### ISSUE THREAD

**Issue by AntoineBx** [sveltia/sveltia-cms#231]
Hello Kioshino! I used to load sveltia into my app like this in Nuxt: 
```
onMounted(async () => {
  window.CMS_MANUAL_INIT = true;

  const CMS = await import("@sveltia/cms");
  const { init } = CMS;

  init({
    config: {
      ...main,
    },
  });
});
```
It worked great but since 0.4 the "main" in your package.json has disappeared, now i have to import it like so
``` 
const CMS = await import("@sveltia/cms/dist/sveltia-cms.js"); 
```
But the init function don't work anymore

I am missing something? thanks

**Comment by kyoshino** [comment]
Hmm, [v0.4.0](https://github.com/sveltia/sveltia-cms/releases/tag/v0.4.0) didn’t make any relevant change. [v0.21.0](https://github.com/sveltia/sveltia-cms/releases/tag/v0.21.0) made the import JS module, and `main` still exists in `package.json`. You can see the [distributed code](https://www.npmjs.com/package/@sveltia/cms?activeTab=code) on npmjs. Do you see any error message?

**Comment by kyoshino** [comment]
Just tested with a SvelteKit project, replacing `onMounted` with `onMount`, and it worked like a charm.

**Comment by AntoineBx** [comment]
Okay sorry about that, i don't really know what happen there. I just did npm remove @sveltia/cms and reinstall it and it was fix. 
I probably mess up with npm update and stuff :sweat_smile:

**Comment by kyoshino** [comment]
No worries, happy to see it solved!
