### ISSUE TITLE
possible bug with combining italics and bold...

### ISSUE THREAD

**Issue by rchrdnsh** [sveltia/sveltia-cms#236]
I have some text in the rich text editor where bold is nested inside italic, but the italic is not rendering properly...

It's written like this in the editor:

```
***Disclaimer**: Once your survey is accepted, you will receive a confirmation and gift card notification. We reserve the right to accept or refuse any and all submissions.*

***Chú ý**:  Sau khi khảo sát của quý vị được chấp nhận, quý vị sẽ nhận được thông báo xác nhận và thẻ quà tặng. Chúng tôi có quyền chấp nhận hoặc từ chối bất kỳ và tất cả các khảo sát nhận được.*
```

...where italic is wrapped around bold, but in the output on the site the italic is gone and there are visible asterisks:

here it is with the italic part not there but the asterisks that should trigger the `<em>` tag are visible instead:

<img width="957" alt="Screenshot 2024-10-30 at 1 59 43 PM" src="https://github.com/user-attachments/assets/243186fe-43ff-4791-a534-eb0483ea97eb">

and what it is in the dev tools:

<img width="600" alt="Screenshot 2024-10-30 at 1 59 51 PM" src="https://github.com/user-attachments/assets/69f2e109-6a20-4967-a966-8ad1b704a239">

no `<em>` at all, just extra asterisks where they should not be...

I don't know if this is a bug or we are not doing something right...but it is very much messing up content writers a bunch...

**Comment by kyoshino** [comment]
Is this an output on your website? Then that’s an issue with the Markdown renderer.

Sveltia CMS itself: The preview looks good — It uses the [Marked.js](https://marked.js.org/) library. But I see the same issue in the editor when I switch between rich text and raw text. It might be a bug in [Lexical](https://github.com/facebook/lexical).

So you could switch to Marked.js.

### editor, rich text off:

<img width="452" alt="image" src="https://github.com/user-attachments/assets/c4f81c0e-02f1-4397-b7f6-8e2b03752a50">

### editor, rich text on:

<img width="457" alt="image" src="https://github.com/user-attachments/assets/aaca8a9e-137b-4f4d-a7d4-c8c00d78cd91">

### preview

<img width="370" alt="image" src="https://github.com/user-attachments/assets/a48f0e70-503e-44d7-b866-e218e15f1ed1">

**Comment by rchrdnsh** [comment]
yeah...thinking it's lexical maybe...

when I first nest it in the rich text editor it looks fine:

<img width="799" alt="Screenshot 2024-10-30 at 2 31 58 PM" src="https://github.com/user-attachments/assets/5ad79bf0-90cc-47ec-8a97-58bf5bf66926">

and it looks correct in the markdown as well:

<img width="805" alt="Screenshot 2024-10-30 at 2 32 15 PM" src="https://github.com/user-attachments/assets/8889f6f9-8409-495c-8029-61a73d8b5ba2">

but when I save and go back again, it no longer looks correct in the rich text editor:

<img width="800" alt="Screenshot 2024-10-30 at 2 32 32 PM" src="https://github.com/user-attachments/assets/323d4710-40f5-4f45-817d-ca1876ad820f">

...as there are visible asterisks where there should not be any...

also, as another issue, the content creator when to use ACTUAL asterisks as well, like this:

<img width="796" alt="Screenshot 2024-10-30 at 2 35 45 PM" src="https://github.com/user-attachments/assets/06b1de9b-d9bc-48d2-bd86-64f1aba3a902">

which seems to ABSOLUTELY DESTROY Lexicals brain...

...soooooo...I dunnooo...🤷🏼‍♂️

**Comment by kyoshino** [comment]
Basically italic text should be wrapped with underscores but Lexical uses asterisks by default. You manually can turn off rich text and replace the leading and trailing asterisks with underscores.

I’ve found a way to force using underscores with Lexical. Will push the change shortly.

**Comment by kyoshino** [comment]
Added the workaround to the [latest version](https://github.com/sveltia/sveltia-cms/releases/tag/v0.45.0), but you might still need to manually replace leading and trailing asterisks with underscores as I said earlier.
