### ISSUE TITLE
Deleted items are restored after page refresh

### ISSUE THREAD

**Issue by 20240816** [sveltia/sveltia-cms#237]
Reproduction steps:
- Delete an item from a collection
- Reload the page
- The deleted item reappears in the CMS (bad) but remains deleted in github (good)

Workaround:
Wipe the site data locally and log back in. E.g. in Firefox wipe here:
![image](https://github.com/user-attachments/assets/792d9e9d-e9c8-4c85-a134-688178c143bb)

**Comment by kyoshino** [comment]
Interesting. Will check!

**Comment by kyoshino** [comment]
Fixed in the [latest version](https://github.com/sveltia/sveltia-cms/releases/tag/v0.45.1) so it shouldn’t happen again. Thanks for the heads-up!
