### ISSUE TITLE
Collections made empty appear populated upon page refresh

### ISSUE THREAD

**Issue by 20240816** [sveltia/sveltia-cms#238]
Deleting all collection items then refreshing the page results in the collection items appearing once again in the CMS but not github

**Comment by kyoshino** [comment]
Maybe you haven’t received the latest version of the CMS. Well, the CMS itself is also cached, and unfortunately it’s unavoidable.

**Comment by kyoshino** [comment]
The CMS script is cached by the CDN for 10 minutes, so sometimes an old version is served just after a new version is published.

**Comment by 20240816** [comment]
It seems to be happening on /@sveltia/cms@0.45.1/dist/sveltia-cms.js

**Comment by kyoshino** [comment]
Hmm, so it should be including the fix for #237. Deleting a single entry and multiple entries are the same process internally, and not sure why the problem still occurs. Will check back tomorrow.

**Comment by kyoshino** [comment]
Added a workaround to [v0.46.2](https://github.com/sveltia/sveltia-cms/releases/tag/v0.46.2). Not 100% sure it fixes the problem, but my test worked fine.
