### ISSUE TITLE
Changes to `widget: string` with `multiple: true` can't be saved alone

### ISSUE THREAD

**Issue by frankbits** [sveltia/sveltia-cms#24]
Changes to `widget: string` with `multiple: true` can only be saved if another field was added before. 
If another field is edited after, the change to the "`string`-`multiple`"-field is reverted. 
Also while editing, the changes are not visualized in the preview.

**Comment by kyoshino** [comment]
I think the [String widget](https://decapcms.org/docs/widgets/#string) doesn’t have the `multiple` option?

**Comment by frankbits** [comment]
> I think the [String widget](https://decapcms.org/docs/widgets/#string) doesn’t have the `multiple` option. You need to use the [List widget](https://decapcms.org/docs/widgets/#list) without `field` or `fields` to save comma-separated strings.

oh, sry... 😄 did confuse those... thanks...
but interestingly it seems to try to do something 🤔🙃

**Comment by kyoshino** [comment]
Looks like the `multiple` property is used in some places without a proper widget type check. I’ll fix them. Sorry for the confusion 🤣 

- https://github.com/sveltia/sveltia-cms/blob/main/src/lib/components/contents/details/preview/field-preview.svelte#L52
- https://github.com/sveltia/sveltia-cms/blob/main/src/lib/components/contents/details/editor/field-editor.svelte#L61

**Comment by frankbits** [comment]
that was me being too stupid to remember the doc😄

but it's probably good to know of this🙃

**Comment by kyoshino** [comment]
Sveltia CMS should have a config validator so users can spot invalid options sooner 🙂 It’s on my todo list but it takes time...
