### ISSUE TITLE
It would be helpful if custom formatters could handle a returned Promise

### ISSUE THREAD

**Issue by mshick** [sveltia/sveltia-cms#244]
It would be quite helpful if custom formatters registered with `registerCustomFormat` could handle a returned Promise, in particular for the `toFile` method.

The practical use-case here is running `prettier.format` (async-only) on contents being written to ensure they conform to a project's code style.

I realize Decap does _not_ support async `toFile` methods. 

The footprint of this change appears to be quite small though, since there are only [two](https://github.com/sveltia/sveltia-cms/blob/main/src/lib/services/contents/draft/save.js#L406) [calls](https://github.com/sveltia/sveltia-cms/blob/main/src/lib/services/contents/draft/save.js#L382) to `formatEntryFile` and both are in the context of `async` functions.

**Comment by kyoshino** [comment]
Sure, it’s probably not a big deal.

**Comment by mshick** [comment]
That's awesome, thanks!

**Comment by kyoshino** [comment]
Shipped [v0.46.0](https://github.com/sveltia/sveltia-cms/releases/tag/v0.46.0) with the async support.

**Comment by kyoshino** [comment]
I’ve just found this Decap issue. It’s closed but Decap doesn’t support async methods as you said. It’s perhaps closed by accident or as wontfix, and I’ve “effectively solved” the very old issue. 🙃 

- https://github.com/decaporg/decap-cms/issues/13

**Comment by mshick** [comment]
Haha, nice! 9 years old! 

Impressive that you're able to knock these out so quickly — a real testament to how much the frontend frameworks have evolved, and your solid code of course.
