### ISSUE TITLE
[Enhancement] Basic markdown support in collection's page (entry/file titles)

### ISSUE THREAD

**Issue by josineto** [sveltia/sveltia-cms#245]
When showing a collection, it would be nice if entry/file titles were rendered using a basic Markdown syntax (like the [one allowed in `description` field](https://github.com/sveltia/sveltia-cms?tab=readme-ov-file#better-collections), but maybe without link support).

Currently, a title such as "A post about *emphasis*" is rendered in collection list as "A post about \*emphasis\*"...

**Comment by kyoshino** [comment]
Got it. There is one more one thing I want to solve:

- https://github.com/decaporg/decap-cms/issues/4350

I’ll take care both.

**Comment by kyoshino** [comment]
Shipped [v0.46.0](https://github.com/sveltia/sveltia-cms/releases/tag/v0.46.0) with the fix.

**Comment by josineto** [comment]
@kyoshino it works as expected, but then I can catch another issue: the sorting of entries is still done without the Markdown rendering, making e.g. entries whose title begins with \*emphasis\* appear as first entry in the list, not in its normal positioning. In the example below, the entry "*Markdown* reference" should be listed between "A post" and "January text", but it's listed as first item:

- *Markdown* reference
- A post
- January text
- Perpendicular text

Sorry, I've only noted this now... Thank you anyway!

**Comment by kyoshino** [comment]
Will check.

**Comment by kyoshino** [comment]
The sorting issue is fixed in [v0.46.2](https://github.com/sveltia/sveltia-cms/releases/tag/v0.46.2)
