### ISSUE TITLE
`script` tag needs `type="module"` for Sveltia CMS to appear in Astro project, but README doesn't say so

### ISSUE THREAD

**Issue by dschuessler** [sveltia/sveltia-cms#246]
I have just tried to migrate my Astro project from DecapCMS to Sveltia CMS, following the [instructions](https://github.com/sveltia/sveltia-cms?tab=readme-ov-file#migration). However, the viewport remained empty when navigating to the admin route.

Through the [zankhq/astro-starter](https://github.com/zankhq/astro-starter) template I found out that the `script` tag needs `type="module"` for Sveltia CMS to work under these circumstances. This is not mentioned in the README.

I don't know when `type="module"` is needed and when it isn't, but I wanted to report back this papercut in case the maintainer(s) want to improve the instructions.

**Comment by kyoshino** [comment]
`sveltia-cms.js` was shipped as an ES module in earlier versions so `type="module"` was needed. [v0.21.0](https://github.com/sveltia/sveltia-cms/releases/tag/v0.21.0) changed the bundle to an IIFE so you no longer need it.

**Comment by ayugioh2003** [comment]
I encountered a similar situation.
I noticed that Astro extracts `<script>` tags and loads them using ESM.
I changed it to the following approach, and it works for importing now:

```html
<script is:inline src="https://unpkg.com/@sveltia/cms/dist/sveltia-cms.js"></script>
```

refs
- https://docs.astro.build/en/guides/client-side-scripts/#script-processing
