### ISSUE TITLE
Sveltia logo flashes before loading configured logo_url image

### ISSUE THREAD

**Issue by 20240816** [sveltia/sveltia-cms#247]
It happens just above here on the GitHub login window for a moment before the configured image replaces it: 
![image](https://github.com/user-attachments/assets/99fba07b-28f8-427a-93e0-8e84e67f7e02)

**Comment by kyoshino** [comment]
Good catch! Should be easy to fix.

**Comment by kyoshino** [comment]
Shipped [v0.46.0](https://github.com/sveltia/sveltia-cms/releases/tag/v0.46.0) with the fix.
