### ISSUE TITLE
Git gateway support

### ISSUE THREAD

**Issue by naton** [sveltia/sveltia-cms#249]
I know this has been discussed and postponed and dismissed here before but I just wanted to highlight how important our current Netlify CMS login setup is for keeping our site updated by my (non tech savvy) colleagues. I can run Sveltia locally and make changes there, which impressed my coworkers a lot, but I must give them bad news when they ask for the same UI being installed on our live site, where they're used to login and edit. 

So, if ever there a gap in the roadmap somewhere, sometime, please 🙏🏻 consider adding support for git gateway too. Thanks again for your work, which I long for using more and more every day.

**Comment by kyoshino** [comment]
Unfortunately, no.

> The Bitbucket, Gitea/Forgejo and Git Gateway backends will not be supported for performance reasons. We may implement a high-performance Git Gateway alternative in the future. We may also support the other platforms if/when their APIs improve to allow the CMS to fetch multiple files at once.
