### ISSUE TITLE
Allow relative links in markdown widget link element

### ISSUE THREAD

**Issue by micvolo** [sveltia/sveltia-cms#253]
Hello Yoshino,
First of all thanks for your amazing work! I ve been loving your project since the start.

I started testing more deeply the project, even if its still in developing, and while i was adding markdown links i found that i can add only external links, not relative to my url.

The button **"link"** remain grey if i dont add **"http://"**

I ve noticed that even if the button is disabled, if you press esc it still works!

<img width="618" alt="image" src="https://github.com/user-attachments/assets/05d427d0-2b6f-474f-ae12-7dfc4b2f2eb9">

thanks for your help!

**Comment by kyoshino** [comment]
Makes sense! Will fix it.

**Comment by kyoshino** [comment]
Fixed in [v0.46.4](https://github.com/sveltia/sveltia-cms/releases/tag/v0.46.4) along with other link insertion issues 🙇🏼
