### ISSUE TITLE
`widget: number` can save `0` only if it was previously another number

### ISSUE THREAD

**Issue by frankbits** [sveltia/sveltia-cms#26]
When you set a number-widget to `0` while it was previously empty, the save-button des not get activated. 
If you change something else too, to activate the save-button, the 0-field does get saved as if it as empty.

Also the field saves an empty string if left empty, even when `required: false`

**Comment by kyoshino** [comment]
> Non-required fields being saved (as empty strings) is actually intentional because missing properties could lead to errors when the data is used/rendered in a framework. It was an annoying thing in Netlify CMS so I’ve changed that behaviour 🙂

Damn, I need to say the current behaviour is inconsistent. I’ll make it right.
