### ISSUE TITLE
0.47.4 NPM package unstyled

### ISSUE THREAD

**Issue by jloh** [sveltia/sveltia-cms#268]
I run Sveltia via NPM and manually init'ing it. I updated to 0.47.4 and noticed that it is unfortunately unstyled, missing most of the CSS classes. Downgrading to 0.47.3 fixes it. The unpkg version of Sveltia _doesn't_ seem to have this problem which is interesting.

0.47.3:
<img width="1286" alt="image" src="https://github.com/user-attachments/assets/8e813028-833f-4584-97ef-dcd974ccf5e6">

0.47.4:
<img width="1286" alt="image" src="https://github.com/user-attachments/assets/4bd32c67-0c6b-42ad-bd2c-a85f031630fc">

**Comment by kyoshino** [comment]
Ugh, sorry about that. Checking what’s happening.

**Comment by kyoshino** [comment]
Fixed in [v0.47.5](https://github.com/sveltia/sveltia-cms/releases/tag/v0.47.5) 🙇🏼

**Comment by jloh** [comment]
Thanks for such a fast fix! Can confirm it's working now. 💪
