### ISSUE TITLE
no line length for editing content with preview turned off...

### ISSUE THREAD

**Issue by rchrdnsh** [sveltia/sveltia-cms#27]
When editing content with preview turned off (nobody wants or uses the preview pane that I know of, including myself)

there is no line length limit, so the editing experience is severely compromised:

for metadata:

<img width="1437" alt="Screenshot 2023-06-18 at 2 50 18 PM" src="https://github.com/sveltia/sveltia-cms/assets/7884263/1221c618-f07b-49ba-8f28-8393f14e18d5">

for body copy (content, etc...)

<img width="1438" alt="Screenshot 2023-06-18 at 2 50 29 PM" src="https://github.com/sveltia/sveltia-cms/assets/7884263/1d22bbc0-2403-4797-9aeb-2cca2b4addaf">

a max line length of 60 to 80 characters would be good, or allowing the user to change it as well. Also, the generally typographic settings are not so hot, as line spacing is not good, font size, etc...

My team and the other teams and people I know who use a CMS NEVER use preview mode, as it is basically useless in every possible conceivable way. They all want an interface more like google docs, MS Word, even Notion style:

Add custom svelte components:

<img width="1193" alt="Screenshot 2023-06-18 at 2 59 26 PM" src="https://github.com/sveltia/sveltia-cms/assets/7884263/5a0fcc84-e567-4c87-b528-a874fe6e2051">

Writing without distractions:

<img width="1197" alt="Screenshot 2023-06-18 at 3 01 15 PM" src="https://github.com/sveltia/sveltia-cms/assets/7884263/c52e99ce-71c6-461a-bc8f-c90a1d82a0ec">

Just want to put these ideas in your heads cuz this is something I really need...

**Comment by kyoshino** [comment]
Thanks for reporting! Will fix the issue shortly ☺️

**Comment by kyoshino** [comment]
I’ll deploy the fix hopefully tomorrow with other updates 🤞🏻

**Comment by rchrdnsh** [comment]
wow, that was quick!

Thank you - ありがとう (dunno if that is correct :-)

**Comment by kyoshino** [comment]
どういたしまして！ – You’re welcome!

**Comment by rchrdnsh** [comment]
I also recommend making the height of metadata fields 48px rather than 32px, which is a but tight...or maybe an option to adjust...maybe a little more of a rounded corner as well :-)
