### ISSUE TITLE
init() requires a configuration file to be present

### ISSUE THREAD

**Issue by FabulousCodingFox** [sveltia/sveltia-cms#271]
init() requires a configuration file to be present, even if the config is passed directly to the init function. This file can be empty and is not used for configuration.

**Comment by FabulousCodingFox** [comment]
![image](https://github.com/user-attachments/assets/45233394-0a15-47a8-a455-08550bf45ad1)
![image](https://github.com/user-attachments/assets/cd1777fb-43a8-44d7-814e-3fd7a36ed7a6)

**Comment by FabulousCodingFox** [comment]
These errors disappear when i create an empty config.yml file in the /public folder

**Comment by kyoshino** [comment]
As [documented](https://decapcms.org/docs/manual-initialization/), you can avoid this by adding `load_config_file: false` to the `config` object. 😉

**Comment by kyoshino** [comment]
Fix landed in [v0.47.7](https://github.com/sveltia/sveltia-cms/releases/tag/v0.47.7).
