### ISSUE TITLE
filter folders by null

### ISSUE THREAD

**Issue by robsonsobral** [sveltia/sveltia-cms#274]
Hi!

Thank you for making a better version of Decap.

May I suggest you to make `filter` parameter of folders to accept `null`, so we can filter for entries **without** a specific field?

Thank you!

**Comment by kyoshino** [comment]
Sure! Should be easy.

**Comment by kyoshino** [comment]
I’ll also solve https://github.com/decaporg/decap-cms/issues/7347 reported today.

**Comment by kyoshino** [comment]
By the way in Sveltia CMS, unlike Decap/Netlify CMS, [all fields are saved even if optional](https://github.com/sveltia/sveltia-cms?tab=readme-ov-file#better-data-output), so the filter may not work as expected. Once the `output.omit_empty_optional_fields` option is added in #241, it will be useful. Anyway I’m going to implement this.

**Comment by kyoshino** [comment]
Solved in [v0.49.0](https://github.com/sveltia/sveltia-cms/releases/tag/v0.49.0).
