### ISSUE TITLE
When settings  "Close the editor after saving a draft" to false all collapsed object and list open themselves

### ISSUE THREAD

**Issue by AntoineBx** [sveltia/sveltia-cms#275]
Helllo Kyoshino! When settings at "Close the editor after saving a draft" to false, 
All previously collapsed list or object with "collapsed: true" in the page reopen unexpectedly

**Comment by kyoshino** [comment]
Fixed in [v0.49.1](https://github.com/sveltia/sveltia-cms/releases/tag/v0.49.1) 🫶

**Comment by rainbowforgedev** [comment]
Hi, this is probably a silly question I'm sorry in advance if so, but for the life of me I can't find how to set up the option to disable auto close on save? It's not in the docs, and nothing I can think of to search on the web or inside the schema https://unpkg.com/@sveltia/cms@0.213.5/schema/sveltia-cms.json or even the git commit referenced in this issue indicates how to actually set the editor to not close on save. Would someone be so kind as to help me out please?

Thanks so much!

**Comment by kyoshino** [comment]
Please use [Discussions](https://github.com/sveltia/sveltia-cms/discussions) for questions.

The feature is [documented](https://sveltiacms.app/en/docs/ui/content-editor#auto-close-editor). It’s not a CMS config option but a user preference option.
