### ISSUE TITLE
All asset entry from select image don't list all images 

### ISSUE THREAD

**Issue by aloxe** [sveltia/sveltia-cms#277]
Hi and thanks for solving issue #156 Regarding the image in the editor, it works well but the "All assets" tab in the "Select image" popup doesn't list all the images as it does in the media section. It only lists the images in the general `media_folder`.

Steps to reproduce and explanations:
- config contains
```
media_folder: "src/static/img"
```
I also use `media_folder: ""` in some collection to import images in the same folder as pages.

Currently, when I have images in both `src/static/img` and `src/pages/` Listing, all media will find all images

![media-section-images](https://github.com/user-attachments/assets/00354af2-b946-4c5c-a4e4-fc9ce77daddc)

But when I want to add one of these images in a page, with select image > All assets I get only the images that are in the `src/static/img` and no images that are in page folders.

![page-edit-select-image](https://github.com/user-attachments/assets/c185bde7-b98f-4f81-9830-d0ab711c7e0f) 

I think it should list all images as well.

**Comment by kyoshino** [comment]
Hmm, this is expected. If you use `media_folder: ''` (an entry-relative image folder), these images are only available to these entries. You cannot use images saved under `documentation` or `part-1` from entries under `examples`, for example.

I think I just need to rename the **All Assets** to **Uncategorized Assets** to avoid confusion.

**Comment by kyoshino** [comment]
As of [v0.49.3](https://github.com/sveltia/sveltia-cms/releases/tag/v0.49.3),
