### ISSUE TITLE
Nothing can be right/control clicked...why?

### ISSUE THREAD

**Issue by rchrdnsh** [sveltia/sveltia-cms#28]
Just noticed this, and it feels a bit odd, but nothing in the UI seems to be right/control clickable...not sure if that is intentional or not, but...I don't know...feels a bit off to me...

That's all :-)

**Comment by kyoshino** [comment]
The browser context menu is intentionally disabled because I wanted to make the CMS more application-ish 🙂 You can still use the context menu on any text fields for spellchecking, etc.

**Comment by rchrdnsh** [comment]
hmmmm...maybe a developer mode option somehow then? It's kinda not so fun to manually rummage through the elements in the dev tools to find stuff when I could right click to inspect, if that makes sense?

**Comment by kyoshino** [comment]
Yeah, it’s okay to enable the context menu on localhost. Will make the change in the next release.

**Comment by kyoshino** [comment]
I’m going to have the developer mode for 2 reasons:

- Even on production, console logs might help, which are currently dumped only when running the dev server
- Custom context menus, not yet implemented in Sveltia CMS, may conflict with the browser’s native context menus

**Comment by kyoshino** [comment]
Forgot to reference this issue but developer mode 🛠 landed in https://github.com/sveltia/sveltia-cms/commit/de447b99a32ca03747e5d8544e02f201dafdc3da. It can be enabled in Preferences!
