### ISSUE TITLE
Weird issue when using local Repo

### ISSUE THREAD

**Issue by Arbee4ever** [sveltia/sveltia-cms#30]
For some reason, whenever I try to use my local repo, it doesn't work and I get the error: "sveltia-cms.js:442 Uncaught (in promise) DOMException: A requested file or directory could not be found at the time an operation was processed." in the console... It worked before, but now seemingly out of nowhere, it doesn't anymore.

**Comment by kyoshino** [comment]
@Arbee4ever Thanks for reporting! It might have regressed at some point. Will check what’s happening later today.

**Comment by kyoshino** [comment]
Can’t figure out the exact reason for the exception, but it could happen, for example, when the project root directory has been moved or renamed. I have added proper error handling to the local backend to avoid the issue. Will deploy the fix later today!

**Comment by Arbee4ever** [comment]
Nice, it works again. Thanks a lot :D
