### ISSUE TITLE
"The backend is not defined in the configuration file"

### ISSUE THREAD

**Issue by pieterdd** [sveltia/sveltia-cms#34]
On a fairly clean install, I see this:

![image](https://github.com/sveltia/sveltia-cms/assets/1407980/d060a6f1-af18-47bd-a258-10363476224c)

Minimally reproducible example at https://storied-cassata-937890.netlify.app/admin/ with the config being loaded from https://storied-cassata-937890.netlify.app/admin/config.yml, which includes this:

```yml
backend:
  name: git-gateway
  branch: main
```

Am I forgetting a config step? It worked with DecapCMS.

**Comment by kyoshino** [comment]
Hey, thanks for checking out Sveltia CMS! Unfortunately, only the GitHub backend is supported at this time, as mentioned in the [README](https://github.com/sveltia/sveltia-cms#compatibility). I can’t provide an ETA to add support for Git Gateway.

**Comment by kyoshino** [comment]
I think the error message is wrong for some reason. I’ll fix it anyway...

**Comment by pieterdd** [comment]
Bingo. I had misunderstood the docs. I had already migrated my repo from GitLab to GitHub specifically for that reason, but didn't realize I should also cut out git-gateway as the middleman.

I assume this will fix my issue. Trying that tomorrow morning. Thanks for the quick response!

**Comment by pieterdd** [comment]
It did! Thanks for the diagnosis. I'll leave the ticket open so the error message can be changed.
