### ISSUE TITLE
Local repository not recognizing posts from remote

### ISSUE THREAD

**Issue by refact0r** [sveltia/sveltia-cms#35]
I have a Sveltekit static site with Sveltia in a Github repo deployed on Netlify. The deployed version of Sveltia correctly recognizes all posts. However when I run the site in development mode locally and select "Work with local repository", Sveltia only displays the posts that were created using the local version. The posts that were pulled from the Github repo are not shown.

**Comment by kyoshino** [comment]
Thanks for flagging the issue! Listing files will be done differently when using the local workflow.

Is this your site in question? https://github.com/refact0r/forgotten-europe-website

**Comment by refact0r** [comment]
Yes that is the site I am working on.

**Comment by kyoshino** [comment]
Okay, will check it out later!

**Comment by kyoshino** [comment]
I’m running your SvelteKit project locally. I see all the content — [2 blog posts, 5 interviews](https://github.com/refact0r/forgotten-europe-website/tree/master/src/content)  and [7 images](https://github.com/refact0r/forgotten-europe-website/tree/master/static/images/uploads) — on Svelta CMS. Not sure what’s going on 🤔 Did you reload `/admin` in your browser after fetching the content from remote?

**Comment by refact0r** [comment]
Yes, I have tried reloading the page, clearing site data, restarting dev server. It seems that all images from remote load correctly, but blog posts, news articles, and the 1 interview not created locally do not show up.

**Comment by kyoshino** [comment]
Hmm, will check again.

**Comment by zanhk** [comment]
Got same problem in my repo https://github.com/zankhq/astro-starter/tree/chore/sveltia

**Comment by zanhk** [comment]
@kyoshino yes I m on windows, it asked for folder permissions and I gave it the whole repo folder access.

I've opened the admin ui with existing file (from the repo that was previously using decap cms) and I did not see them, I've created a new entry and it created the file succesffully, after restarting I could only see the created file and not the previous one.

As you mentioned could probably be a permission issue, I ll take a look when I ll have sometime but if it's only a local problem doesn't seem a big deal as it's always possibile to change those files directly, just mentioned as I was testing out the repo.

**Comment by kyoshino** [comment]
Let me check with my Windows virtual machine later today.

**Comment by kyoshino** [comment]
Testing on Windows 10 but cannot reproduce the issue. 🤔 🤔 🤔  Fetch the origin, reload the CMS, and then remote changes show up in the admin. I suspected it might be related to file paths because Windows uses a backslash as the separator, but not sure.

Has anyone noticed any difference between a file created locally and a file created remotely?

**Comment by kyoshino** [comment]
Or perhaps line breaks, because Windows uses CR+LF while macOS/Linux/web uses LF.

**Comment by kyoshino** [comment]
Now I could reproduce the issue. Figuring out why!

**Comment by kyoshino** [comment]
So line breaks are the culprit. 🤖 This kind of issue can be avoided by configuring the `.gitattributes` file (and optionally `.editorconfig`, see [this commit](https://github.com/videomark/videomark/pull/201/files)) on a repository, but anyway, the problem could be easily solved in the CMS.

**Comment by kyoshino** [comment]
The fix is in! Sorry to take this long 🙇🏼

**Comment by zanhk** [comment]
@kyoshino Awesome

**Comment by zanhk** [comment]
@kyoshino This works as well!
