### ISSUE TITLE
Allow external image src

### ISSUE THREAD

**Issue by refact0r** [sveltia/sveltia-cms#37]
I have set the `media_folder` setting to a folder within the `/src` folder of my Sveltekit site, as I want to use vite-imagetools to transform and optimize all images. This means that the images would not be available through a direct path like they would in `/static`, and so their thumbnails don't show up in Sveltia's image library. Thus I would like to see external image urls being allowed for the `public_folder` setting. Maybe it would be even better to have a separate option for the path of Sveltia's image thumbnails vs the path written into the markdown files.

**Comment by kyoshino** [comment]
Hey, thanks for filing the issue! Yeah, I know there are some cases image previews don’t work. The site mentioned in #6 has the same issue with vite-imagetools. I’ll figure out how to work around it soonish.

**Comment by refact0r** [comment]
It seems like having images in `/static` and importing from there works somehow, but Sveltekit really doesn't like it and gives constant console warnings.

**Comment by kyoshino** [comment]
I have fixed the issue indirectly in https://github.com/sveltia/sveltia-cms/commit/6ba93d605aaafa82545486d6bdcae02a73684b3f now shipped as [v0.5.3](https://github.com/sveltia/sveltia-cms/releases/tag/). Just like Netlify CMS, the preview files will now be loaded from GitHub through the [API](https://docs.github.com/en/rest/git/blobs#get-a-blob), not from the production site.
