### ISSUE TITLE
media-select-popup broken

### ISSUE THREAD

**Issue by frankbits** [sveltia/sveltia-cms#41]
clicking on replace-/add-button for image-widget opens an empty `<form>` and blocks the page until it's reloaded.
Of course you also can't add images like this.
I don't know since which version this happens, as I just noticed it.

**Comment by kyoshino** [comment]
Thanks for your report! 🙏🏻 Hmm, I can reproduce the issue with the production version but not locally. Investigating.

**Comment by kyoshino** [comment]
Deployed the fix 🙇🏻
