### ISSUE TITLE
DateTime-widget loads `pm`-time as `am`

### ISSUE THREAD

**Issue by frankbits** [sveltia/sveltia-cms#45]
If DateTime has for example `20:00` saved, opening the element in the CMS loads DateTime with `08:00`.

The check if the element has been altered and can be saved, does check correctly. 
-> opening + save  = unwanted change to datetime

**Comment by kyoshino** [comment]
@frankbits Can you please paste the widget configuration here?

**Comment by frankbits** [comment]
```
      - name: "datetime"
        label: "Date & Time"
        widget: datetime
```

**Comment by kyoshino** [comment]
Confirmed and deployed the fix. Thanks for the report!
