### ISSUE TITLE
add error handling of github api errors

### ISSUE THREAD

**Issue by nosovk** [sveltia/sveltia-cms#46]
Time to time GitHub API can go down, and make responses with 5xx codes and body like that:

```json
{
   "data": null,
   "errors":[
      {
         "message":"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `DF4A:6E1B:1D670F9:1DAA64D:64E7DC75` when reporting this issue."
      }
   ]
}
```

It would be nice to show some error modal with "Retry" button to retry the request.
No errors silently ignored :(

**Comment by kyoshino** [comment]
Netlify CMS has a background service status check and shows an alert when the Git backend is down.

https://github.com/decaporg/decap-cms/pull/3889

I think we need this and took a screenshot before:

<img width="348" alt="Screenshot 2023-02-17 at 11 42 58 PM" src="https://github.com/sveltia/sveltia-cms/assets/2929505/a9d77b25-03ab-4ad5-95d5-510e3b9d215d">

The English label is

> The backend service is experiencing an outage. See %{details} for more information
