### ISSUE TITLE
if we have one article = one directory setup, then folder not deleted upon article removal.

### ISSUE THREAD

**Issue by nosovk** [sveltia/sveltia-cms#47]
If we make use of we use [Folder Collections Path](https://decapcms.org/docs/beta-features/#folder-collections-path) and [Folder Collections Media and Public Folder](https://decapcms.org/docs/beta-features/#folder-collections-media-and-public-folder) for content structure setup we have issue with folder deletion.

We got structure like that:
```
content/article1/index.md
content/article1/image1.jpg
content/article2/index.md
content/article2/image2.jpg
```
If we are going to delete `article1` from sveltia, then `content/article1/index.md` removed, but the folder with contents (`content/article1/image1.jpg`) still persists. We expect that folder deleted with an article and all related images.

Proposed solution: add flag to delete folder with all content.

**Comment by kyoshino** [comment]
I’m aware of the same issue in Netlify/Decap CMS: https://github.com/decaporg/decap-cms/issues/6642

Will figure out how it could be done in Sveltia CMS.
