### ISSUE TITLE
Unable to insert Unsplash API key

### ISSUE THREAD

**Issue by SanBen** [sveltia/sveltia-cms#5]
Unable to enter the unsplash API key.

![image](https://user-images.githubusercontent.com/6377076/235377191-a9df5420-12ed-4282-82b9-7b0a4ff6811d.png)

After getting the key as instructed by the links, I'm unable to press the 'insert' button.

**Comment by kyoshino** [comment]
@SanBen Thanks for the heads-up! Looks like the API key validation is wrong. I’ll fix the regex to support 40 character with hyphens. In the meantime, please revoke your key to prevent it from being used by someone else.

**Comment by kyoshino** [comment]
The fix now deployed. Please reload the CMS and try again!

**Comment by SanBen** [comment]
> The fix now deployed. Please reload the CMS and try again!

It works! Wow that was fast! 😉 Issue can be closed.

**Comment by kyoshino** [comment]
Yay! 🙌🏻
