### ISSUE TITLE
markdown editor

### ISSUE THREAD

**Issue by nosovk** [sveltia/sveltia-cms#52]
Would be nice to add some markdown editor for non tech writers.
For example https://github.com/BearToCode/carta-md or something else

**Comment by kyoshino** [comment]
Yes, Sveltia really needs the Markdown support. I’ve just found Carta in the [Svelte blog post](https://svelte.dev/blog/whats-new-in-svelte-september-2023) but it doesn’t seem to support WYSIWYG editing. I’ll merge this issue with #32 to explore options.
