### ISSUE TITLE
if `identifier_field` is set (not default to title), `slug` has to be also set

### ISSUE THREAD

**Issue by frankbits** [sveltia/sveltia-cms#56]
An entry can't be saved, if `identifier_field` is set, but not `slug`.
`identifier_field` should also change the default of `slug`

https://decapcms.org/docs/configuration-options/#slug:
> a different field can be used via [identifier_field](https://decapcms.org/docs/configuration-options/#identifier_field)

Also it can't anymore be saved, if no `title`-field exists when no `identifier_field` or `slug` is set.
I've had a collection set up this way, and it just saved the entries with a random id (chars and numbers).

**Comment by frankbits** [comment]
also this has had to be functional at some time, as this problem appears for a collection I've used like this successfully for some time

**Comment by kyoshino** [comment]
In the previous versions of Sveltia CMS, if a slug could not be determined, it automatically used a random slug. I removed the fallback at some point because it might be confusing. I’ll fix the `identifier_field` issue and restore the fallback code.

**Comment by kyoshino** [comment]
The fix is in! Thanks for the report 💯

**Comment by frankbits** [comment]
I wouldn't have a problem with there being no random fallback. 
But either way it would be nice, if the error-message wouldn't just say "there was some error. try again later.", as this gives no info what caused it (hat to search for a while) and "trying later" does nothing ...

**Comment by kyoshino** [comment]
I’ll improve the error message 😅
