### ISSUE TITLE
Include branch in Git Repository link

### ISSUE THREAD

**Issue by dsgibbons** [sveltia/sveltia-cms#58]
My site is configured to use a branch other than main/master. The Git Repository link always takes me back to main/master. Can this be configured to go to the branch specified in `config.yml` instead?

**Comment by kyoshino** [comment]
I think I can fix this quickly. The current link just goes to `https://github.com/[owner]/[repo]` (default branch) but it has to be `https://github.com/[owner]/[repo]/tree/[branch]`.

**Comment by kyoshino** [comment]
The fix is in!

**Comment by dsgibbons** [comment]
Thank you for the quick fix!
