### ISSUE TITLE
Sort, Filter and Group by element in "list" widget

### ISSUE THREAD

**Issue by Arbee4ever** [sveltia/sveltia-cms#59]
I have a widget that with multiple values inside, would it be possible to make "sortable_fields" accept something like "list[0].field" to sort by that field?

**Comment by kyoshino** [comment]
Just checked the [code](https://github.com/sveltia/sveltia-cms/blob/main/src/lib/services/contents/view.js#L142-L159) and I think I can fix it quickly. The [Netlify/Decap CMS doc](https://decapcms.org/docs/configuration-options/#sortable_fields) actually shows a nested field like `language.en` but I’ve overlooked such cases. So it’s a bug in Sveltia 🙃

**Comment by Arbee4ever** [comment]
Oh... but would that also allow accessing array elements with array[index]?

**Comment by kyoshino** [comment]
Sveltia CMS uses the [flat](https://www.npmjs.com/package/flat) library to “flatten” objects/arrays. For an array, the field name would be something like `list.0.field` 🙂

**Comment by kyoshino** [comment]
The fix is in! 🎉
