### ISSUE TITLE
slug configuration for svelte-kit

### ISSUE THREAD

**Issue by nosovk** [sveltia/sveltia-cms#6]
I have a few sites on a svelte kit, and they all mostly depend on https://github.com/pngwn/MDsveX
It means that content stored inside repo in files like that:
```
src/routes/letters/Ivan/+page.svelte.md
src/routes/letters/Piotr/+page.svelte.md
...
src/routes/letters/{slug}/+page.svelte.md
```

or
```
src/routes/blog/my-first-post/+page.svelte.md
src/routes/blog/my-second-post/+page.svelte.md
...
src/routes/blog/{slug}/+page.svelte.md
```

I can't find a way, how to explain which files should be edited in collections config.

Actually I tried
```
    folder: "/src/routes/letters/{{slug}}"
    slug: "+page.svelte.md"
```
but it ignores interpolation.
Or:
```
    folder: "/src/routes/letters/"
    slug: "{{slug}}/+page.svelte.md"
```
but it ignores folder creation...

It there a way to store each file in separate folder?

Also is there some option to store assets in the articles folder?

**Comment by nosovk** [comment]
It seems that interpolation in folder key should fix an issue

**Comment by kyoshino** [comment]
Hey @nosovk, thanks for filing an issue! I know MDsveX but not really using it for now. Your files are Frontmatter, right? Do you have a sample site I can clone?

**Comment by nosovk** [comment]
I've send an invite to https://github.com/NodeArt/BusinessforUkraine/tree/main/src/routes/what-we-do
unfortunately it's not public repo.

**Comment by nosovk** [comment]
format of files is frontmatter in markdown

```
---
published: true
title: title
date: 24.11.2022
snippet: snippet
description: description
thumbnailImg: ./CountDown_post.png
---
text
```
but it seems that problem is not with file format, but with routing. I mean that each article has separate folder

**Comment by nosovk** [comment]
I found that similar structure is here: https://github.com/MailCheck-co/mailcheck.site/tree/master/src/routes/blog
but it uses a bit outdated version of sveltekit. But the content structure is the same.

**Comment by kyoshino** [comment]
Thanks! I’ll check them out soonish!

**Comment by kyoshino** [comment]
I already checked the source briefly 🙂 Other than the proper Frontmatter handling, I think I need to add support for the [Markdown widget](https://decapcms.org/docs/widgets/#markdown) (my client also needs it) and [relative image folder path](https://decapcms.org/docs/beta-features/#folder-collections-media-and-public-folder) to Sveltia CMS so your site can rely on it. I’ll take some time this week to get things done!

**Comment by kyoshino** [comment]
Just a quick update: regarding the slug/path configuration, I think what’s missing in Sveltia CMS is the support for [Folder Collections Path](https://decapcms.org/docs/beta-features/#folder-collections-path). Let’s see how it works!

**Comment by nosovk** [comment]
Yep, it seems that next chapter "Folder Collections Media and Public Folder" also related

**Comment by kyoshino** [comment]
Right, I’m implementing both.

**Comment by kyoshino** [comment]
Sorry, it’s taking time to deal with relative path media folders. This ticket is still a priority. 🇺🇦

**Comment by nosovk** [comment]
No problem, we are not in a hurry

**Comment by kyoshino** [comment]
Sorry to keep you waiting!! [Folder Collections Path](https://decapcms.org/docs/beta-features/#folder-collections-path) and [Folder Collections Media and Public Folder](https://decapcms.org/docs/beta-features/#folder-collections-media-and-public-folder) have been implemented. I’m going to have a Markdown editor soonish.

**Comment by nosovk** [comment]
I've made a new attempt to add Sveltia to BFU.
https://github.com/NodeArt/BusinessforUkraine/pull/789

It seems that folder structure now handled properly.
Even assets stored in correct folder (with a small problem, but in correct folder, which is great).

But I stuck with date_format. I agree that moment.js a bit obsolete in 2023, but is there some solution to make date conversion?

We should get date: `01.05.2023` but get `2023-08-22T07:43:00.000Z`

**Comment by kyoshino** [comment]
Sorry for the overall delay in my work! 🙇🏻 Well, it’s better to use the ISO format in the JSON data and use moment.js to format dates in the frontend. But I think the current behaviour is incompatible with Netlify CMS and is just a bug in Sveltia CMS. Fixing now.

**Comment by kyoshino** [comment]
In the meantime, I think you can use the `format` property instead of `date_format` for formatting.

**Comment by kyoshino** [comment]
I just checked the doc for the [DateTime widget](https://decapcms.org/docs/widgets/#datetime) (since the [Date widget](https://decapcms.org/docs/widgets/#date) has been deprecated) and realized that `date_format` and `time_format` are for _display formats in the UI_, which Sveltia CMS doesn’t (or perhaps won’t) support. So I think you need to use the `format` property anyway 😅

**Comment by nosovk** [comment]
You were right!
<img width="1336" alt="image" src="https://github.com/sveltia/sveltia-cms/assets/1398808/838b53db-3f2a-402f-a47c-44fc1d80dbae">
we have invalid format in UI, but correct in md file! https://github.com/NodeArt/BusinessforUkraine/pull/789/commits/1ee4ea9e3a4c47084deed12ea2f16fd1886f5611

**Comment by nosovk** [comment]
But there is one strange behavior. When I use local mode - only posts created by sveltia available inside it, none of existent posts available.

**Comment by nosovk** [comment]
it could be related to https://github.com/sveltia/sveltia-cms/issues/35
I have no hosted version of sveltia yet, but local behavior is the same - not all items are shown.

**Comment by kyoshino** [comment]
When I check out your `svelte` branch and open the CMS, I see 10 blog posts (or “letters” ) that match the local files. Don’t know why I cannot reproduce the issue on my Chrome. 😓

**Comment by kyoshino** [comment]
Perhaps related to file permissions. Do you see any errors in the console? Which post is missing?

**Comment by nosovk** [comment]
Yep, version hosted with proxy shows all articles.
Feel free to check: https://sveltia.businessforukraine.pages.dev/admin/
it's linked to branch for now, just for testing.

Local setup still doesn't show existing articles. But it's not a problem at all if hosted version works.

**Comment by nosovk** [comment]
It seems that if we use [Folder Collections Path](https://decapcms.org/docs/beta-features/#folder-collections-path) and [Folder Collections Media and Public Folder](https://decapcms.org/docs/beta-features/#folder-collections-media-and-public-folder) then folders related to article are not removed when article deleted.

**Comment by nosovk** [comment]
In common integration works. @kyoshino big thanks for putting your efforts into support.
We will do some testing and go to prod with Sveltia.
I will open new tickets to corner cases that we will meet further.
