### ISSUE TITLE
Git Gateway backend is not supported

### ISSUE THREAD

**Issue by DannieBGoode** [sveltia/sveltia-cms#68]
![image](https://github.com/sveltia/sveltia-cms/assets/4180198/2109a940-6e3a-465e-a57f-76515f38e964)

I have a fully functional Decap CMS website with the code in [Github](https://github.com/DannieBGoode/summit-advisors) and hosted in Netlify.
When I change the [one-line ](https://github.com/DannieBGoode/summit-advisors/blob/master/admin/index.html#L13) and I try to load it I get the error in the image above.

This is my [config.yml](https://github.com/DannieBGoode/summit-advisors/blob/master/admin/config.yml).

What could be wrong here?

**Comment by kyoshino** [comment]
Hi, thanks for checking out Sveltia CMS. As the message says, Git Gateway is not yet (and probably won’t be) supported in Sveltia. Please take a look at the [Compatibility](https://github.com/sveltia/sveltia-cms#compatibility) section in the README.
