### ISSUE TITLE
The configured proxy backend is not supported

### ISSUE THREAD

**Issue by zanhk** [sveltia/sveltia-cms#69]
First of all I just found this repo and I think it's a very cool project.

![image](https://github.com/sveltia/sveltia-cms/assets/17980844/7fe9beda-08b8-4563-8d37-1861cb71043d)

I'm trying to access the admin ui on localhost.

The configuration that I m using is this one https://github.com/zankhq/astro-starter/tree/chore/sveltia/public/admin

Probably is just me not reading the full documentation but do you have an idea of what I am doing wrong?

I get the error with both `local_backend` property set or not

**Comment by kyoshino** [comment]
Thanks for checking out Sveltia CMS! I _think_ it’s a simple bug in Sveltia. WIll take a look now.

**Comment by zanhk** [comment]
@kyoshino thanks if you need help to debug or test I have the repo open I can try help you

**Comment by kyoshino** [comment]
The fix deployed! Please reload the app and try again.

**Comment by zanhk** [comment]
Awesome it worked thanks, you should add a donation button

**Comment by kyoshino** [comment]
Thanks for your confirmation! I’ve just added a sponsor link (again) to the repo 😆

**Comment by kyoshino** [comment]
Thank you 🙏🏼 🙏🏼 🙏🏼

**Comment by eur2** [comment]
@zanhk Great repo! Is Astro working well with SveltiaCMS and content in markdown, especially with images? It seems that your images are optimized by Astro right? But they don't have a relative path in your markdown but still working?

**Comment by zanhk** [comment]
@eur2 thanks, was about to open an issue about that, it works great with decap cms but seem there is a problem here where the image get prepended by a "/", I've created this issue https://github.com/sveltia/sveltia-cms/issues/72

**Comment by eur2** [comment]
@zanhk Good to know because with netlify-cms, the image wasn't using relative path in markdown. So Astro couldn't optimize them.
