### ISSUE TITLE
If no matching files (md,json,...) are found, graphql request is wrong

### ISSUE THREAD

**Issue by Arbee4ever** [sveltia/sveltia-cms#7]
When the folder provided in the config.yml doesn't exist/has no [matching](https://github.com/sveltia/sveltia-cms/blob/ee83e9192d3f9440e46b637f49c6298da3f1d042/src/lib/services/parser.js#L33) files inside, [this](https://github.com/sveltia/sveltia-cms/blob/ee83e9192d3f9440e46b637f49c6298da3f1d042/src/lib/services/parser.js#L18) returns empty filelists, which causes the [graphql query](https://github.com/sveltia/sveltia-cms/blob/ee83e9192d3f9440e46b637f49c6298da3f1d042/src/lib/services/backends/github.js#L99) to be incorrect.

It returns:
```
"query {\n    repository(owner: \"<OWNER>\", name: \"<NAME>\") {\n      \n    }\n  }"
```
(notice the curly brackets with only whitespace characters inside)

GitHub then returns:
```
{"errors":[{"message":"Parse error on \"}\" (RCURLY) at [4, 5]","locations":[{"line":4,"column":5}]}]}
```

Which then causes an Error (Chromium) in the javascript stopping the whole Load process:
```
caught (in promise) TypeError: Cannot destructure property 'repository' of '(intermediate value)' as it is undefined.
```

This should either:
	- load the CMS with an empty list if folder is empty
	- notify the User that folder doesn't exist

**Comment by kyoshino** [comment]
Thanks for the report! The GraphQL query should be skipped for sure. I’ll take care of it later today.

**Comment by kyoshino** [comment]
The fix is now deployed! 🚀
