### ISSUE TITLE
public_folder automatically prepended by /

### ISSUE THREAD

**Issue by zanhk** [sveltia/sveltia-cms#72]
In decap cms I was used to set media and public image folder like this:

`media_folder: "src/assets/images"`

`public_folder: "@assets/images"`

As they are placed inside src folder and processed, the decap cms output was something like this

`heroImage: "@assets/images/blog-placeholder-3.jpg"`

https://github.com/zankhq/astro-starter/blob/chore/sveltia/src/content/blog/it/first-post.md

In sveltia a / is automatically addead at the start of the string resulting in 

`heroImage: /@assets/images/blog-placeholder-2.jpg`

This break the page as  /@assets/images/blog-placeholder-2.jpg it's not a valid path.

Is there a way to fix it or some workaround?

Thanks

**Comment by kyoshino** [comment]
The fix is in!

**Comment by zanhk** [comment]
@kyoshino Awesome thanks, when back home I ll try again

**Comment by zanhk** [comment]
@kyoshino It works! Thanks

**Comment by zanhk** [comment]
This is just a minor detail but looks like that sometimes the preview image is not visible as it point to

![image](https://github.com/sveltia/sveltia-cms/assets/17980844/7b9d6e1f-d46b-404e-b9cf-a0377aadef95)

`@assets/images/blog/blog-placeholder-3.jpg`

![image](https://github.com/sveltia/sveltia-cms/assets/17980844/88c28746-05ea-49e5-afc1-d636a3941996)

---

Clearing site data seem to solve the problem 

![image](https://github.com/sveltia/sveltia-cms/assets/17980844/892b49f8-e724-4efc-9902-e3fc4bd9ae0d)

as after cleaning the site data the image source is settet like this

![image](https://github.com/sveltia/sveltia-cms/assets/17980844/14e7c490-3100-4c59-b6f9-f7cb02d78002)


blob:https://astrostarter.zank.studio/b3d11537-ce63-46b0-9cde-a1d9e1813658


is there a way to make sure it's always setted like this?

**Comment by kyoshino** [comment]
Will figure out how it could happen.

**Comment by zanhk** [comment]
Seem like images on assets folder have the same problem 

![image](https://github.com/sveltia/sveltia-cms/assets/17980844/3f7c08a2-5a39-491a-a10c-d008eb3b16f9)

**Comment by kyoshino** [comment]
Just shipped the fix! It was certainly due to the cache thing. 🙇🏼

**Comment by zanhk** [comment]
> Just shipped the fix! It was certainly due to the cache thing. 🙇🏼

Awesome!
