### ISSUE TITLE
Support for Dynamic Media Folder Paths per Post

### ISSUE THREAD

**Issue by deployn** [sveltia/sveltia-cms#74]
Hello,

I'm currently seeking a way to configure individual media folders for each post. In Netlify CMS, you can achieve this by setting the `media_folder` and `public_folder` paths dynamically based on the slug like so:

```yaml
media_folder: '{{slug}}'
public_folder: '{{slug}}'
```

However, this approach doesn't seem to work in Sveltia. When I try to set the path to /src/content/blog/{{slug}}, the directory is incorrectly created with the literal name "{{slug}}" rather than substituting the actual post slug.

Additionally, I need to maintain locale-specific directories within the blog folder, like this:

```
blog
|
├── en
│   └── something.md
├── de
│   └── something.md
└── something
    └── image.png
```

Is there currently a way to have a separate directory for each post's media while also keeping the locale directories intact? Any guidance or workaround would be greatly appreciated.

**Comment by kyoshino** [comment]
Assuming you’re using [Folder Collections Media and Public Folder](https://decapcms.org/docs/beta-features/#folder-collections-media-and-public-folder)... When I see the Sveltia code, `{{slug}}` seems already supported. I’ll figure out why it’s not working.

And okay, you use the i18n support. I actually saw you posted a comment on https://github.com/decaporg/decap-cms/issues/4781 and realized that Sveltia has the same issue here. I’m happy to fix it.

**Comment by deployn** [comment]
Thanks for the reply. I'll try again with the slug directory. If you say it's supported, I'm sure the problem is on my end.
