### ISSUE TITLE
Support for toml-format not working

### ISSUE THREAD

**Issue by frankbits** [sveltia/sveltia-cms#8]
When "toml" is selected as format (/extension), the "Save" of a new Element, ...
... generates an empty toml-file, if working on the local repo.
... throws an Error in the CMS-UI, if working with github.

**Comment by kyoshino** [comment]
Hey @frankbits, thanks for reporting! I’ll check the issue this afternoon.

**Comment by kyoshino** [comment]
The fix is now deployed! 🚀 Please reload the CMS and try again!
