### ISSUE TITLE
Ctrl + F not working inside a collection detail

### ISSUE THREAD

**Issue by zanhk** [sveltia/sveltia-cms#87]
Ctrl + G seem to still work but Ctrl + F isn't working

[google_screen_recording_2023-12-23T16-46_32.901Z.webm](https://github.com/sveltia/sveltia-cms/assets/17980844/fb941b8d-11ae-4601-ad44-18229fa8c3c5)

**Comment by kyoshino** [comment]
I was actually thinking about adding a field search bar to the editor itself as part of the solution to https://github.com/decaporg/decap-cms/issues/7011. For now, I’ll just enable the `Ctrl+*` keyboard shortcuts.

**Comment by kyoshino** [comment]
The fix is in!

**Comment by zanhk** [comment]
Awesome!
