### ISSUE TITLE
Hard to input spaced words in list widget

### ISSUE THREAD

**Issue by zanhk** [sveltia/sveltia-cms#88]
In the "list" widget it's hard to input multiple words that contains space in between, for example when i need to input a list of tags where the tags are composed by multiple words.

[google_screen_recording_2023-12-23T17-10_25.859Z.webm](https://github.com/sveltia/sveltia-cms/assets/17980844/28b14112-a0d7-4f77-90c1-e29f9f335c47)

**Comment by kyoshino** [comment]
Thanks for the heads-up! I came up with a simple workaround. I’ll overhaul the simple list UX early next year.

**Comment by kyoshino** [comment]
The fix is in!

**Comment by zanhk** [comment]
Awesome!
