### ISSUE TITLE
Can't develop locally in WSL

### ISSUE THREAD

**Issue by MineTechOficial** [sveltia/sveltia-cms#92]
Whenever I try to open it, chrome says it can't open it because it contains system files, although it is my home directory

**Comment by kyoshino** [comment]
Thanks for reporting. It seems the issue is due to a [restriction in Chrome](https://www.google.com/search?q=%22because+it+contains+system+files%22), which is unavoidable in Sveltia CMS, unfortunately. https://github.com/coder/code-server/issues/4646 has some workarounds you could try.

**Comment by MineTechOficial** [comment]
It worked, thx! I just needed to nest it in another folder (very secure security method, chrome)
